### ISSUE TITLE
alltube.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#1016]
Reklama z oszustwem
![Zrzut ekranu z 2019-11-08 04-47-03](https://user-images.githubusercontent.com/36385327/68448170-e5ed6b00-01e2-11ea-821f-01db367b6cfa.png)

**Comment by krystian3w** [comment]
tv teraz otwiera pl?

**Comment by krystian3w** [comment]
Wszystkie 3 warianty mają przekierowanie na: https://www.alliance4creativity.com/watch-it-legally/
