### ISSUE TITLE
[próba 1] cyberrescue.me

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#1037]
Święta za miesiąc a wcześniej:

- black friday,
 - cyber monday,
- i dzień darmowej wysyłki,
- ...no i mikołajki 

także żniwa zakupowe zapasem, dlatego warto przejrzeć tę listę: 

> https://pl.cyberrescue.me/lista-podejrzanych-sklepow-internetowych/

Może coś jeszcze dośle, zawsze to parę osób uchronionych przed oszustami, wszystkich zachęcam do podawania potencjalnych podejrzanych e-sklepów.

`hawkeye` zostaw ten temat jako ogólny, może ktoś dołączy przed żniwami.

**Comment by krystian3w** [comment]
Niby już 33 strony były dawno zablokowane.

**Comment by hawkeye116477** [comment]
To jest z czerwca, niektóre też mogły już wygasnąć.

**Comment by krystian3w** [comment]
Jak skrypt nie da rady sprawdzić whois, to się najwyżej ręcznie sprawdzi ~66 domen.

Niby lepiej offline usuwać jak whois wygaśnie (chyba że to darmowa subdomena) niż po komunikacie przeglądarki "nie znaleziono strony".

**Comment by blocker999** [comment]
coś takiego znalazłem ( może się przyda )

http://di.com.pl/kontroluj-swoje-wyciagi-bankowe-cyberprzestepcy-zarabiaja-na-falszywych-subskrypcjach-64204

**Comment by krystian3w** [comment]
Takie sobie:

`moviestarplanet.pl` - gra F2P...?

**Comment by krystian3w** [comment]
No chyba że zdesperowane dzieci bawią się w cyberprzestępczość by nabić na konto płatny fejm...

**Comment by hawkeye116477** [comment]
Oryginalne źródło: https://pl.cyberrescue.me/lista-platnych-subkskrypcji/, jest tam tego więcej, ale raczej chyba to się nie kwalifikuje do KADa, czytać trzeba uważnie i tyle...

`design-builder.io` - jest trial na 3 dni, trzeba zabulić 2 eur, jak się nie wycofamy, to płacimy 69 eur co 30 dni dopóki nie anulujemy.

Jakby tak na to patrzeć, to chyba i Platformę Canal+/CP musielibyśmy zablokować, bo mają pakiety dodatkowe na parę miesięcy za darmo i też automatycznie przedłużają i trzeba bulić jak się nie zrezygnuje.
