### ISSUE TITLE
alltube.com.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1050]
### Link bezpośredni 
`https://alltube.com.pl`
### Dodatkowe informacje mogące mieć znaczenie
"Następca" Filmoteki - #894

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Lub prościej podróbka z wciśniętym "`com`".

**Comment by krystian3w** [comment]
Wszystkie 3 warianty mają przekierowanie na: https://www.alliance4creativity.com/watch-it-legally/
