### ISSUE TITLE
alltube.com.pl

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#1061]
Ta reguła `||alltube.com.pl^` na stronie http://alltube.tv wycina obrazki na stronie głównej.

**Comment by krystian3w** [comment]
Opcjonalnie można zmienić na `~image` i zobaczyć czy AdGuard rozumie, że nie wolno blokować obrazków.

**Comment by krystian3w** [comment]
Ktoś wie czy po zakupie premium za 20 zł ma się filmy w tym `alltube.com.pl`?

**Comment by krystian3w** [comment]
Wszystkie 3 warianty mają przekierowanie na: https://www.alliance4creativity.com/watch-it-legally/
