### ISSUE TITLE
szukajka.tv

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1367]
### Link bezpośredni 
`https://szukajka.tv/`
### Dodatkowe informacje mogące mieć znaczenie
oszustwo

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
To jest tylko wyszukiwarka video, choć fakt, część linków nie działa. Koparka jest już blokowana przez listę NoCoin.

@krystian3w Koparki z NoCoin przenosimy do KADa?

**Comment by krystian3w** [comment]
Ja bym nie kopiował, bo pewnie nie nadążymy nad optymalizacją / aktualizacją.

Może przy bilansie oszustw (zostają klikalne linki do `alltube.com.pl` i innych 💩) dodać blokadę dokumentu jak z otube / cda-hd.

**Comment by hawkeye116477** [comment]
Ewentualnie schować linki do fałszywych `szukajka.tv##a[href*="filmyonline.com.pl"]`.

**Comment by krystian3w** [comment]
Zobaczę ile ich znajdę, mam już 4 domeny.

**Comment by hawkeye116477** [comment]
@krystian3w A nie lepiej po prostu `szukajka.tv##[href*="alltube.com.pl"], [href*="filmyonline.com.pl"], [href*="fili.com.pl"], [href*="twoje-seriale.tv"]`?

**Comment by krystian3w** [comment]
Ja bym dodał `<A>`, by nie leciał CSS przez 507 elementów a tylko 42.

**Comment by krystian3w** [comment]
Zbanowali wyszukiwarkę (sic!) - https://www.alliance4creativity.com/watch-it-legally/
