### ISSUE TITLE
alltube.com.pl

### ISSUE THREAD

**Issue by xxcriticxx** [FiltersHeroes/KAD#1401]
opinia jest wasza ja mysle zeby to zablokowac

**Comment by hawkeye116477** [comment]
Tyle, że to jest już blokowane. No chyba, że chodzi o hosts.

**Comment by xxcriticxx** [comment]
sorry wrong repo

**Comment by krystian3w** [comment]
Blokowane lekko, bo niby wersja `.pl` i `.tv` jakoś używa `.com.pl` jako mirror grafik.

**Comment by krystian3w** [comment]
Ban trudny do cofnięcia: https://www.alliance4creativity.com/watch-it-legally/
