### ISSUE TITLE
planeta.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1465]
### Link bezpośredni 
`https://www.planeta.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Planeta.pl jest typowym dezinforumjącym tabloidem, stworzonym najpewniej przez Rosjan i mieszającym ostro w naszych sprawach. Poziom tego tabloida jest mocno żenujący i Super Express i Fakt ze swoimi "fejkami" to przy nich są święci. Do niedawna ich teksty były tłumaczone zwykłym translatorem na jezyk polskim i dlatego można było się domyślić prosto, że to nie jest "nasza" polska robota. Teraz zatrudnili jakiegoś korektora z Polski, bo przestali robić typowo translatorskie debilne pomyłki czy tam literówki. Zresztą widać po zawartości tego szajsu, że ich celem jest mieszanie w głowach Polaków. Do pewnego czasu tabloid był mało znany, ale od paru miesięcy jest on często przytaczany przez przeglądarkę Edge w ich wbudowanym kanale informacyjnym, który można także bezpośrednio odpalić z innej przeglądarki. Tutaj przykład tego gówna z dziś https://www.planeta.pl/Ciekawostki/COVID-19-dreczy-ozdrowiencow.-Wypadna-im-wszystkie-wlosy

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
Kolejny przykład

https://demagog.org.pl/fake_news/nie-koronawirus-nie-jest-bronia-biologiczna/
