### ISSUE TITLE
[próba 2] cyberrescue.me

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#1555]
https://cyberrescue.info/lista-podejrzanych-sklepow-internetowych/ widzieliście to?

testowałem na kilu linkach jak 24papierosy – https://24papierosy.pl/ i wyświetla się.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/1037

**Comment by MajkiIT** [comment]
@krystian3w dzięki

**Comment by xMaap** [comment]
Nie dałoby rady pobierać linki z tej strony jak z legalniewsieci?

**Comment by hawkeye116477** [comment]
Jakby napisali tak ładnie jak w LWS, to może...

**Comment by xMaap** [comment]
Ok rozumiem. Jeszcze jak możecie przejrzeć to https://github.com/PolishFiltersTeam/KAD/issues/1241#issuecomment-790201608 i dodać do KAD.
