### ISSUE TITLE
ges.vg

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1649]
### Link bezpośredni 
`http://ges.vg/zz50`
### Dodatkowe informacje mogące mieć znaczenie
Podejrzany link z niechcianego SMS

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Oliwera się provident, czyli pożyczki.

Skraczaczy linków staramy się nie blokować, bo potem właściciele usługi są zawiedzeni.
