### ISSUE TITLE
Koparki BTC - nieaktywne/wyrejestrowane

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1685]
### Dodatkowe informacje mogące mieć znaczenie

```
smectapop12.pl
berserkpl.net.pl
cdn-analytics.pl
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Jak na stronach są koparki lub one udostępniają kod do kopania to należy próbować to zgłosić do list anty "Web-Coin-Miner":

Potencjalne dobre miejsce na zgłoszenie koparki | Nazwa listy
--- | ---
https://github.com/uBlockOrigin/uAssets/issues/new | "uBlock filters – Resource abuse"
https://github.com/hoshsadiq/adblock-nocoin-list/issues/new | "NoCoin Filter List"
https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/new| "CoinBlockerLists by ZeroDot1 uBlock" <br><sup>(This list disables browser based miners such as coin-hive)</sup>

**Comment by krystian3w** [comment]
Strony zdają się być offline lub wymagają podania specyficznej subdomeny by uzyskać połączenie.

> `Brak informacji o domenie w bazie Registry NASK [NOT_EXIST]`
