### ISSUE TITLE
chomikuj.pl

### ISSUE THREAD

**Issue by nastavoi** [FiltersHeroes/KAD#1747]
### Dodatkowe informacje mogące mieć znaczenie
Przy próbie wejścia w obojętnie jaki odnośnik do ```chomikuj.pl``` z poziomu wyszukiwarki google, otrzymuję komunikat, że załadowanie strony było niemożliwe z uwagi na regułę ```||chomikuj.*^$document,domain=~chomikuj.pl```. Czy takie działanie jest właściwie/zamierzone? Przy bezpośrednim wejściu żadnego ostrzeżenia nie ma.

**Comment by krystian3w** [comment]
Takie działanie jest błędne dla http://chomikuj.pl, dopisać trzeba by "google":

`||chomikuj.*^$document,domain=~chomikuj.pl|~google.*`

Lub to błąd w uBO 1.35.0.

**Comment by nastavoi** [comment]
Na AdGuard 7.6 for Windows nightly 40 reguła ```||chomikuj.*^$document,domain=~chomikuj.pl``` uniemożliwia wejście na chomikuj z poziomu google, natomiast na uBO 1.35.0 tego problemu nie ma. Po dopisaniu do reguły ```|~google.*``` jest ok na AG. Błąd w AG?

**Comment by krystian3w** [comment]
Raczej błąd w logice aplikacji AdGuard, może ona nie ma "już"* szansy wykryć czy to już domena chomikuj.

\* - Jeszcze można zobaczyć czy 7.5 ma to samo - jak nie to świeży bug jak coś odświeżali/napisali na nowo.

**Comment by AdamWr** [comment]
Zgaduję, że to ten sam problem/błąd co tutaj - https://github.com/AdguardTeam/CoreLibs/issues/1421, ale szczerze mówiąc nie wiem, czy to zostanie naprawione ¯\\_(ツ)_/¯

**Comment by krystian3w** [comment]
Z oznakowań raczej nie, ktoś by się musiał uprzeć by aplikacja zachowywała się jak dodatek.

Niby w AdGuardowej technologi regex nie lubi dla `all` i `doc` samego tld dla domeny:

https://github.com/PolishFiltersTeam/KAD/blob/2afc78c97d10c53789cfad53effc5d61156fd27c/sections/specjalne_AG.txt#L4-L7

a w uBO to nie był problem pewnie od wczesnych wydań z planszą "ścisłej blokady":

https://github.com/PolishFiltersTeam/KAD/blob/2afc78c97d10c53789cfad53effc5d61156fd27c/sections/przekrety.txt#L18-L21

**Comment by Lukjan38** [comment]
mi ublock origin, blokuje strona, ze to oszustwo.

**Comment by krystian3w** [comment]
Bo lecisz po http, wymuś `https://` i będzie ok.
