### ISSUE TITLE
przekręty typu: `/^https?:\/\/[\w]{9,32}\.[a-z-]{6,16}(\.com)?\.pl/` 

### ISSUE THREAD

**Issue by hawkeye116477** [FiltersHeroes/KAD#1753]
`http://4fb9729a93.natrasiekorzysci.pl/` i wiele więcej podejrzanych w Google można znaleźć.

`created:               2021.04.27 18:10:13`

**Comment by krystian3w** [comment]
Znaczy wyłapać 99.9% subdomen czy bawić się w drugie laboratorium Malware Google/Eset?

**Comment by hawkeye116477** [comment]
Możesz poddać głębszej analizie jak chcesz, może coś tam jeszcze znajdziesz, a parę subdomen do KADhosts.

Znalazłem inne:
```
902258356.clubretro.com.pl
1297875865.rekrutacjaksos.pl
2443130266.petrolhub.pl
697b62c4d23a312a649e8dc0ca182352.devstartup.pl
3487987441.parafiagoscino.pl
```

**Comment by krystian3w** [comment]
Ja mam ~131 i bot usunął duplikaty:


https://github.com/PolishFiltersTeam/KADhosts/commit/ba3674da77b4b64a8acd0ec2903d9acd7f565341
