### ISSUE TITLE
n-eats.site

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1868]
### Link bezpośredni 
`https://n-eats.site/`
### Dodatkowe informacje mogące mieć znaczenie
Przy próbie zakupu przekierowuje na fałszywą stronę banku którą KAD już blokuje
`https://secure.t-pay.tech/payments/86b4dd12-7e6ef9d62df960ef-2df960efef273a33-ef273a33`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
@krystian3w https://github.com/PolishFiltersTeam/KAD/commit/b4c9efc114145e9b4acbb3a0939fe21f5c62c99e
