### ISSUE TITLE
b-time.pw

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#1927]
### Link bezpośredni do strony zawierającej oszustwo
`https://b-time.pw/PwM6n59N?external_id=iyi546j6ihqzoc7hkfo5&creative_id=404670&campaign_id=184610&publisher_id=DZAHIGM7ON&utm_campaign=mb&utm_source=ht&utm_medium=pl_pop&utm_term=ht_pl_pop_win_sz_4022`

**Comment by hawkeye116477** [comment]
Ktoś tu chyba od 2 października nie aktualizował listy.

**Comment by krystian3w** [comment]
Mamy FP:

`https://translate.google.com/translate?sl=de&tl=tr&u=https://allegrolokalnie.pl/`

Mają formularz do FP?
