### ISSUE TITLE
bialywidelec.pl | optimalbox.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#1934]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
bialywidelec.pl
optimalbox.pl
```

### Dodatkowe informacje mogące mieć znaczenie

https://www.wykop.pl/link/6317793/fitboxy-gdzie-moje-zamowienie-a-raczej-gdzie-moje-pieniadze/
To samo co https://github.com/FiltersHeroes/KAD/issues/1921

**Comment by krystian3w** [comment]
Z maila

### Link bezpośredni
`https://optimalbox.pl/`

## Dodatkowe informacje mogące mieć znaczenie

https://optimalbox.pl/\nhttps://bialywidelec.pl/
https://www.wykop.pl/link/6317793/fitboxy-gdzie-moje-zamowienie-a-raczej-gdzie-moje-pieniadze/
https://www.wykop.pl/artykul/6284521/catering-dietetyczny-jak-piramida-finansowa-czyli-jak-zarabiac-oszukujac-ludzi/

Zgłoszenie opublikowane anonimowo przez użytkownika.
