### ISSUE TITLE
[NSFW] casualdates-here.life

### ISSUE THREAD

**Issue by FadeMind** [FiltersHeroes/KAD#1949]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://casualdates-here.life/?u=q21paew&o=w3bkce7&t=BALARAM&cid=QkFMQVJBTSxQTCwxNzguMjM1LjE0Ny4yMzIsV0VCLExPU1BPTExPUw&x=3
```

### Dodatkowe informacje mogące mieć znaczenie

Scam na Instagramie. 
![20211031-1635704342](https://user-images.githubusercontent.com/9846948/139596625-560747a8-967e-4d9e-bfb4-5de48a4195f3.png)

1. Obserwuje cię  randomowe konto z ładną dziewczyną w profilowym.
2. W stopce ma magiczny adres `https://l.instagram.com/?u=https%3A%2F%2Fbit.ly%2F3pQFS7d&e=ATOzc2EO8PhQke8iYTuOVvXLIxuST-BEJ_yqDc92XXYchak1JtSakZ0ASqMtuS0_r3AoWD6Rw9261IroQhN4AvA&s=1`
3. Adres wskazany wyżej przekierowuje do strony z randomowym scamem NSFW

**Comment by krystian3w** [comment]
Regex poprawiony
