### ISSUE TITLE
orlen-news.biz

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#1971]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
orlen-news.biz
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2021-11-22 20-46-03](https://user-images.githubusercontent.com/36385327/142925244-28c068c7-a9e2-44a3-8555-9464acb71893.png)

**Comment by krystian3w** [comment]
```json
[
    {
        "RegisterPositionId": 36836,
        "DomainAddress": "orlen-news.biz",
        "InsertDate": "2021-11-22T20:49:37",
        "DeleteDate": null
    }
]
```

Dla bota offline lub przekroczył "`quotę`".

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/commit/6b27f1eff98ac83681c708e365881a955f073967#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R14643
