### ISSUE TITLE
lotina.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1972]
### Dodatkowe informacje mogące mieć znaczenie
Sprzedają fałszywe perfumy (Channel albo Tom Ford nigdy nie będzie kosztował 139PLN). Brak NIP. KRS czy adresu kontaktowego w regulaminie sklepu.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
Niedługo pojawi się w aktualizacji https://github.com/FiltersHeroes/KAD/commit/3616e7a0ff225b8f83be14e3a1b97e1739d11fa1#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R1

**Comment by krystian3w** [comment]
Duplicate of #1241
