### ISSUE TITLE
blokada w comodo dragon

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#1977]
Na stronie `czasdzieci.pl/warszawa/`
gdy po klikam w książke "gwiazdkowy prosiaczek" blokuje link

`chrome-extension://ffjgpapimgnmibnacmeilgjefnoofefp/warning/alert.html?type=Malware&targeturl=https://bit.ly/3czXNHt`

![cd](https://user-images.githubusercontent.com/23176832/143678666-e5e1e871-ed81-4530-8d2c-fdeed8c87ca0.png)

**Comment by xMaap** [comment]
Comodo nie powinien tego blokować.
`https://bit.ly/3czXNHt`
Gdzie przekierowuje do
`https://www.empik.com/gwiazdkowy-prosiaczek-rowling-j-k,p1275974159,ksiazka-p`
Może Comodo ogólnie blokuje skracacz od bitly.com.

**Comment by krystian3w** [comment]
Zgłoś to do twórcy przeglądarki, KAD to nie Teresa z Kalkuty do wyręczania biednego Blocker999, bo zna tylko francuski.

**Comment by krystian3w** [comment]
Zgłoś to do twórcy przeglądarki, KAD to nie Teresa z Kalkuty do wyręczania biednego Blocker999, bo zna tylko francuski.

**Comment by krystian3w** [comment]
Zgłoś to do twórcy przeglądarki, KAD to nie Teresa z Kalkuty do wyręczania biednego Blocker999, bo zna tylko francuski.

**Comment by krystian3w** [comment]
Zgłoś to do twórcy przeglądarki/dodatku "Online Security Pro", KAD to nie Matka Teresa z Kalkuty do wyręczania biednego Blocker999, bo zna tylko francuski.

ID dodatku wskazuje że masz: https://chrome.google.com/webstore/detail/online-security-pro/ffjgpapimgnmibnacmeilgjefnoofefp

Spróbuj go chamsko odinstalować z Dragon i problem pewnie zniknie.
