### ISSUE TITLE
Cryptominer XMRig

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#1991]
### Link bezpośredni 
`https://occt.pro`
### Dodatkowe informacje mogące mieć znaczenie
via https://zaufanatrzeciastrona.pl/post/sprzedajesz-komputer-uwazaj-na-ten-nowy-nietypowy-rodzaj-ataku/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
- U mnie na dwóch ISP jest offline
- whois do grudnia 2022, widać jakieś ślady banowania przez/powołując się na np. ICANN
- brak polonizacji
- konto @occtpro ma jakiś error 404 (może oznaczone jako spam bez kasacji)

**Comment by ClusterByte-x** [comment]
https://github.com/FiltersHeroes/KAD/pull/1990

Niestety, brak polonizacji. Strona offline. Istnieją jeszcze inne warianty - warto wysyłać do laboratorium antywirusowego (np. Kaspersky, Arcabit) lub do CERT Polska.

**Comment by krystian3w** [comment]
Znaczy news wysłać, bo ja nie mam żadnego honeypot a allegro lokalnie unikam.

**Comment by ClusterByte-x** [comment]
@krystian3w  
Wysłałem do Arcabit (pomoc@arcabit.pl). Został zaklasyfikowany jako `Trojan.Agent.FQRD` ([VirusTotal](https://www.virustotal.com/gui/file/586bdd45de7cdf9d0a5c7a3c9223f29e23d9e87a7fd76564bc87dfae0a4b6568)).
