### ISSUE TITLE
redundant filters

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#2]
`fb-szpieg.com.pl has been made redundant by fb-szpieg.com`
`hdvod24.pl has been made redundant by vod24.pl`

???

**Comment by azet12** [comment]
Niektórzy uzytkownicy mogą źle wyświetlająca się domenę zinterpretować jako błąd blokowania w adblocku, przy czym go wyłączają - skutki są oczywiste, strona i skrypty nie są blokowana w ogóle, a użytkownik jest zagrożony. Dlatego w KAD blokowane jest wszystko.

**Comment by xxcriticxx** [comment]
zbedne filtry ale stare strony jeszcze dzialaja

**Comment by MajkiIT** [comment]
@azet12 ok dzięki za info.
