### ISSUE TITLE
Automatyczne usuwanie domen usuniętych z listy CERT

### ISSUE THREAD

**Issue by mimi89999** [FiltersHeroes/KAD#2003]
Domeny usunięte z listy ostrzeżeń CERT powinny być automatycznie usuwane z listy KAD.

**Comment by krystian3w** [comment]
Są usuwane ręcznie (nieregularnie), jak dotąd tylko 93 banicje cofnęli (liczę też te z "www." jakiego w uBo i AG banować nie trzeba, bo z urzędu blokowane są subdomeny i "www." jako subdomena).

Jak masz na myśli wygasłe przekręty to zazwyczaj co tydzień nasz "Playground" wypluwa domeny zaparkowane i z wygasłym whois. Jedynie około 100 wisi w pliku "nieznane" (np. limit zapytań padł lub domena z whois wyleciała, że aż nie mamy daty zakończenia usługi - chociaż takie lubi gromadzić aftermarket.pl).


Utrudnieniem w usuwaniu będzie przejście na plik co zawiera datę kasacji bana (json, XML, tsv z końcówką ".csv").

**Comment by krystian3w** [comment]
#1999

**Comment by mimi89999** [comment]
Czemu macie tak długi okres aktualizacji? Lista ostrzeżeń jest aktualizowana co 5 min.

Też uważam, że chyba najlepiej byłoby rozdzielić te listy i łączyć je na końcu.

**Comment by mimi89999** [comment]
> o ile nie padnie z przeciążenia od sprawdzania z 12 tysięcy domen (Circle CI ich stan czy zwarcają odpowiedź robi w 7 minut a GitHub Action dobija do 30 min)

Próbowaliście z aiohttp lub httpx?

**Comment by krystian3w** [comment]
Najpewniej by nie wyczerpać darmowych "1000 minut" akcji w CircleCI (konkretny limit pewnie będzie w regulaminie usługi lub w panelu po zalogowaniu). W dawnym Travis CI limit akcji wyczerpywał sam projekt "EI" przy spontanicznie aktualizowanym pliku "ppb.txt"

Na GitHub Actions pewnie trzeba  by mocno okroić sprawdzanie pliku txt jak nowych domen nie sortują a lecą na górę lub dół albo MS się obrazi i zablokuje akcje lub dostęp do repo aż nie zmniejszymy obciążenia.

**Comment by krystian3w** [comment]
> Próbowaliście z aiohttp lub httpx?

Mnie bardziej ciekawi ile zostaje oznaczonych jako "chwilowo offline" a bez pełnej ścieżki przekrętu nie będzie statusu np. "202".

**Comment by mimi89999** [comment]
> > Próbowaliście z aiohttp lub httpx?
> 
> Mnie bardziej ciekawi ile zostaje oznaczonych jako "chwilowo offline" a bez pełnej ścieżki przekrętu nie będzie statusu np. "202".

To też jest problem. Te które się nie rozwiązują na pewno są offline. Co do reszty, to nigdy nie można mieć pewności.

**Comment by hawkeye116477** [comment]
> Próbowaliście z aiohttp lub httpx?

Korzystaliśmy tylko i wyłącznie z komendy host w Bashu. Jakoś wątpię, by coś w Pythonie wyszło szybciej.

**Comment by mimi89999** [comment]
> > Próbowaliście z aiohttp lub httpx?
> 
> Korzystaliśmy tylko i wyłącznie z komendy host w Bashu. Jakoś wątpię, by coś w Pythonie wyszło szybciej.

Sprawdzanie jest wolne nie z powodu ograniczeń sprzętowych, tylko ograniczeń sieci. Skrypt czeka na to aż żądanie zostanie przesłane do serwera, serwer na nie odpowie i odpowiedź trafi do niego. asyncio pozwala wykonywać wiele operacji IO (czyli np. sieciowych) równolegle.

**Comment by hawkeye116477** [comment]
Ok, tak czy siak, nie wiem czy wiele żądań na raz to taki dobry pomysł, czy się ktoś nie obrazi...  Wiem, że, np whois strzela focha przy takich akcjach. Tak, widziałem, że można ustalić ile ma być max zapytań równolegle, ale nadal jakoś się waham. Cóż, pomyślimy, a na razie dodałem usuwanie usuniętych z CERT :smile:.

**Comment by mimi89999** [comment]
Widzę, że lista została odświeżona, ale usunięte domeny nadal tam są np. https://github.com/FiltersHeroes/KAD/blob/master/KAD.txt#L14617

**Comment by hawkeye116477** [comment]
Zabrakło jq, więc nie wyszło. Dlatego też dopisałem do obrazu i uruchomiłem ponownie parę minut temu.

**Comment by mimi89999** [comment]
> Wiem też, że np whois strzela focha przy takich akcjach.

Czy odpytujecie whois? Jeśli tak, to gdzie?

**Comment by hawkeye116477** [comment]
> Czy odpytujecie whois? Jeśli tak, to gdzie?

W przypadku CERTa nie, jedynie raz na tydzień w celu [sprawdzenia wygasłych domen](https://github.com/FiltersHeroes/ScriptsPlayground/blob/master/scripts/DSC.sh).

**Comment by krystian3w** [comment]
Zakładając, że przekręty cert są u każdego możliwego rejestratora domen, to pewnie nie można wszystkiego wrzucać w jakiś multiserwer, dla przykładu domeny eu w 99% muszą być pytane poprawnie z pomocą "api" `eurid.eu`.

**Comment by hawkeye116477** [comment]
Melduję, że zadanie zostało wykonane => https://github.com/FiltersHeroes/KAD/commit/ed77d9bbcd7621f55b6651cc5df475f4fd6ac660 :stuck_out_tongue: .

**Comment by krystian3w** [comment]
Jeszcze chętny musiałby sprawdzić czy nie mamy jakiś:

`||nagrania-covid-*.ct8.pl^`

zamiast

`nagrania-covid-19.ct8.pl`
