### ISSUE TITLE
allegrolokalnie.pl a blokada w aplikacji AdGuard

### ISSUE THREAD

**Issue by juhacz** [FiltersHeroes/KAD#2009]
### Bloker (Blocker)

AdGuard

### Link bezpośredni, na którym występuje problem

```markdown
https://allegrolokalnie.pl/
```

### Opis błędu

Z tym wpisem coś jest nie tak:

`||allegrolokalnie.$document,domain=~allegro.pl|~allegrolokalnie.pl|~wp.pl`

### Dodatkowe informacje mogące mieć znaczenie

Używam aplikacji dla Windows w najnowszej wersji 7.8, mam również zainstalowany plugin do przeglądarki "Asystent przeglądarki AdGuard".

**Comment by hawkeye116477** [comment]
Ten wpis mówi blokuj strony zaczynające się od `allegrolokalnie.` bez `https://allegrolokalnie.pl/` i jest poprawny.
Jeżeli AdGuard to blokuje, to w takim razie jest to błąd po jego stronie. Jaką masz wersję AdGuarda i czy jest to rozszerzenie do przeglądarki czy może przypadkiem aplikacja dla Windowsa?

**Comment by juhacz** [comment]
Używam aplikacji dla Wiondows w najnowszej wersji 7.8, mam również zainstalowany plugin do przeglądarki "Asysten przeglądarki AdGuard".
Próby wejścia na:
https://allegrolokalnie.pl/
https://www.allegrolokalnie.pl/
zawsze kończą się komunikatem z AdGuard
AdGuard uniemożliwił załadowanie tej strony z powodu następującej reguły filtrowania
||allegrolokalnie.$document,domain=~allegro.pl

**Comment by hawkeye116477** [comment]
CC @AdamWR

**Comment by krystian3w** [comment]
Naprawią w AdGuard 8 lub 8.1

**Comment by AdamWr** [comment]
Wygląda na błąd.
Otworzyłem ponownie to zgłoszenie - https://github.com/AdguardTeam/CoreLibs/issues/1421
