### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2011]
### Link bezpośredni 
`https://www.dobreprogramy.pl/macrium-reflect-free,program,windows,6628615210137729`
### Dodatkowe informacje mogące mieć znaczenie
Uwalona strona: brak opisu programu, brak linków do programu, wycięta środkowa sekcja przez KAD.

Jak jest:
![1](https://user-images.githubusercontent.com/74409207/147926663-fec1317b-b7d9-492a-ba01-e6a58de8738c.png)

Jak powinno być:
![2](https://user-images.githubusercontent.com/74409207/147926652-d8fc6877-1ca0-46b6-99b5-6ba53862220a.png)

Uwalone przez:
![3](https://user-images.githubusercontent.com/74409207/147926810-6cd7d6cc-2cf5-4751-8d1d-d6c73639bca8.png)

Zgłoszenie opublikowane przez użytkownika **felix-22**.

**Comment by krystian3w** [comment]
Screen powinno być zawiera również błąd, filter ma na celu blokowanie buttona generującego link do adware w domenach tymczasowych Amazon.

**Comment by freezer2022** [comment]
Screenshoot jest poglądowy idioto, był robiony pod kątem uwzględniającym błąd, a nie filtr, przedstawia ogólny zarys co było popsute (brakująca sekcja), felix nie zagłębiał się i nie analizował co ma wycinać filtr, bo nie miał akurat tym razem takiej potrzeby ani chęci / ochoty, a to, że czasem to robi, to nie znaczy, że zawsze musi.
