### ISSUE TITLE
pilny-przekaz.eu

### ISSUE THREAD

**Issue by mino815** [FiltersHeroes/KAD#2012]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://pilny-przekaz.eu/
```

### Dodatkowe informacje mogące mieć znaczenie

Strona z fake newsem wyłudzająca login i hasło do Facebooka:

![1Screenshot_20220103-194535_Firefox](https://user-images.githubusercontent.com/47322804/147974381-08ac8c10-3367-40ee-9c01-6bda94ccea88.png)
![2Screenshot_20220103-194437_Firefox](https://user-images.githubusercontent.com/47322804/147974394-6c9e324c-c6f1-4c33-8109-400073b4032e.jpg)
![3Screenshot_20220103-195435_Firefox](https://user-images.githubusercontent.com/47322804/147974414-f6f894e9-6157-4fa3-9348-aa019882ba12.png)
![4Screenshot_20220103-195444_Firefox](https://user-images.githubusercontent.com/47322804/147974424-ba3e7076-8df2-42aa-bede-0dc02a983b6f.png)
![5Screenshot_20220103-195449_Firefox](https://user-images.githubusercontent.com/47322804/147974436-1f132386-0513-4788-981d-669755d3113d.png)

**Comment by krystian3w** [comment]
Można taki phishing zgłaszać do CERT i jak się wyrobią w 8 godzin z rana lub następnie 3 czterogodzinnych odstępach to nam doda pan bot @PolishRoboDog
