### ISSUE TITLE
wyko.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2013]
### Dodatkowe informacje mogące mieć znaczenie
Strona podszywająca się pod wykop.pl? Proszę o sprawdzenie.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
```
>>> https://wyko.pl

> --------------------------------------------
> 200 OK
> --------------------------------------------
Status:	200 OK
Code:	200
Server:	nginx
Date:	Wed, 05 Jan 2022 00:30:27 GMT
Content-Type:	text/html; charset=UTF-8
Connection:	close
Set-Cookie:	locale=en_US; expires=Sat, 03-Jan-2032 00:30:27 GMT; Max-Age=315360000; path=/
```

Na razie od 4 lat się nic nie zmieniło.

**Comment by hawkeye116477** [comment]
Przekierowuje na `https://www.wykop.pl/link/3782311/reprezentacja-polski-korzysta-z-elektrostymulacji/`. Ponoć wcześniej były inne przekierowania => `https://www.wykop.pl/link/3782311/comment/56961325#comment-56961325`, ale raczej nic podejrzanego.
