### ISSUE TITLE
surf-chiny.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2016]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
surf-chiny.com/pl/
```

### Dodatkowe informacje mogące mieć znaczenie

Wygląda jak phishing surfshark.com

**Comment by krystian3w** [comment]
```
Registrant Organization: Surfshark ltd
Registrant State/Province: Tortola
Registrant Country: VG
```

**Comment by krystian3w** [comment]
Mnie wygląda na próbę obejścia problemu z banem na poziomie chińskiego firewalla.
