### ISSUE TITLE
Crypto scam

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2026]
### Link bezpośredni 
`https://polskagroups.space/`
### Dodatkowe informacje mogące mieć znaczenie
https://polskagroups.space/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
>         "RegisterPositionId": 43374,
>         "DomainAddress": "polskagroups.space",
>         "InsertDate": "2022-01-19T11:28:09",
>         "DeleteDate": null
