### ISSUE TITLE
Scam Bitcoin na Szymona Hołownie

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2030]
### Link bezpośredni 
`https://pl.market-host.com/Holow_new/`
### Dodatkowe informacje mogące mieć znaczenie
Kolejna odmiana tego
https://www.dobreprogramy.pl/szymon-holownia-wykorzystany-przez-oszustow-znany-schemat-nowy-bohater,6628705383884417a

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`W trosce o Twoje bezpieczeństwo zespół CERT T-Mobile zablokował do niej dostęp by uniemożliwić próbę ataku lub wyłudzenia.`

**Comment by krystian3w** [comment]
```json
[
    {
        "RegisterPositionId": 43780,
        "DomainAddress": "pl.market-host.com",
        "InsertDate": "2022-01-21T21:38:35",
        "DeleteDate": null
    },
]

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/commit/be57cc3a276c65f9a478036cb3a593b6f9099d28#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R18040
