### ISSUE TITLE
prodfolk.email

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2031]
### Link bezpośredni 
`https://prodfolk.email/`
### Dodatkowe informacje mogące mieć znaczenie
Kolejna odmiana tego
https://www.dobreprogramy.pl/szymon-holownia-wykorzystany-przez-oszustow-znany-schemat-nowy-bohater,6628705383884417a

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Zobaczymy czy do 13 zbanuje to CERT Polska i jak szybko będzie offline.

**Comment by krystian3w** [comment]
```json
[
  {
    "RegisterPositionId": 43883,
    "DomainAddress": "prodfolk.email",
    "InsertDate": "2022-01-23T02:31:47",
    "DeleteDate": null
  }
]
