### ISSUE TITLE
puls-biz.space

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2034]
### Link bezpośredni 
`https://puls-biz.space/`
### Dodatkowe informacje mogące mieć znaczenie
Scam Bitcoin na Roberta Lewandowskiego

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Zgłoszone do CERT.

**Comment by krystian3w** [comment]
```json
[
    {
        "RegisterPositionId": 44062,
        "DomainAddress": "puls-biz.space",
        "InsertDate": "2022-01-24T17:27:14",
        "DeleteDate": null
    }
]
```

https://github.com/FiltersHeroes/KAD/commit/11cbef0d65421d0e28aed905d6809dd5ff51d964#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R18145
