### ISSUE TITLE
dot-sync.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2038]
### Link bezpośredni 
`http://dot-sync.com/`
### Dodatkowe informacje mogące mieć znaczenie
Scam Bitcoin na Dawida Kubackiego 

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
> "RegisterPositionId": 44421,
> "DomainAddress": "dot-sync.com",
> "InsertDate": "2022-01-25T17:40:00",
> "DeleteDate": null
