### ISSUE TITLE
guboshlepa.email

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2039]
### Link bezpośredni 
`https://guboshlepa.email/`
### Dodatkowe informacje mogące mieć znaczenie
Scam Bitcoin na Szymona Hołownie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
> "RegisterPositionId": 44452,
>         "DomainAddress": "guboshlepa.email",
>         "InsertDate": "2022-01-26T02:56:40",
>         "DeleteDate": null
