### ISSUE TITLE
onlinetorgnews.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2040]
### Link bezpośredni 
`https://www.onlinetorgnews.com/`
### Dodatkowe informacje mogące mieć znaczenie
Scam Bitcoin na Szymona Hołownie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
![](https://urlscan.io/screenshots/bdc2cf49-070e-4db2-8e82-f0297a2cd8e5.png)

**Comment by krystian3w** [comment]
Ban cert.

**Comment by krystian3w** [comment]
Zostawiam otwarte, może trzeba dodać do CERT SKIP.
