### ISSUE TITLE
unionfxtradingpro.com | crypto-guild.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2044]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
unionfxtradingpro.com
crypto-guild.com
```

### Dodatkowe informacje mogące mieć znaczenie

https://forexrev.pl/ostrzezenia-28-01-capital-crypto-trade-invest-area-crypto-portion/

**Comment by ClusterByte-x** [comment]
unionfxtradingpro.com - brak polonizacji?

**Comment by ClusterByte-x** [comment]
`unionfxtradingpro.com` - brak polonizacji?

**Comment by xMaap** [comment]
U po jakimś czasie tłumaczy automatycznie.

**Comment by krystian3w** [comment]
Jest jakaś maszynowa sekundę po załadowaniu.
