### ISSUE TITLE
Adguard przestał aktualizować KAD.

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2046]
Zauważyłem, że Adguard przestał aktualizować KAD i wszystko co zostało dodane od 27 stycznia 20:09 CET do filtru nie jest blokowane https://github.com/FiltersHeroes/KAD/commit/d13c7e202778c8b856a5e1e2eb5c230ba3640308.
W uBlock Orgin działa jak powinno i to dzieje się w Chrome jak i w Firefox.
![Zrzut ekranu z 2022-01-29 19-50-10](https://user-images.githubusercontent.com/36385327/151673678-b2534a6c-d8ac-47c4-b085-6785db289842.png)

**Comment by xMaap** [comment]
Polskie Filtry Elementów Irytujących również
![Zrzut ekranu z 2022-01-29 20-00-29](https://user-images.githubusercontent.com/36385327/151674034-87a9d25a-98e1-4e9a-8fef-13107b2dc437.png)

**Comment by krystian3w** [comment]
Tak to jest jak nie piszą czemu robią dezaktywację np. błędy w pobieraniu pliku suplementu lub informacji że jakiś filtrów nie chcą widzieć u siebie.

**Comment by AdamWr** [comment]
Wygląda na to, że problem z aktualizacją filtrów dotyczy wszystkich "list trzecich", już to zgłosiłem, ale nie wiem jak szybko zostanie to naprawione.

**Comment by krystian3w** [comment]
Jak nie zgłaszałeś ręcznie e-mailem to fajnie będzie śledzić numer issue subskrypcją lub w RSS wasze forum dla osób co nie lubią github.

**Comment by AdamWr** [comment]
Zgłosiłem na wewnętrznym czacie.

**Comment by AdamWr** [comment]
Wygląda na to, że problem został naprawiony.

**Comment by krystian3w** [comment]
Dodatkowo od jakiegoś czasu wypadły 2 cykle z 8 i lista jest sprawdzana co 4 godziny (trochę szkoda).
