### ISSUE TITLE
wypadek-wosp.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2047]
### Link bezpośredni 
`http://wypadek-wosp.pl`
### Dodatkowe informacje mogące mieć znaczenie
Phising, fałszywa strona wyłudzająca dane logowanie do serwisu Facebook

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
> "RegisterPositionId": 45476,
>         "DomainAddress": "wypadek-wosp.pl",
>         "InsertDate": "2022-01-30T13:09:07",
>         "DeleteDate": null

**Comment by ClusterByte-x** [comment]
> "RegisterPositionId": 45476,
>         "DomainAddress": "wypadek-wosp.pl",
>         "InsertDate": "2022-01-30T13:09:07",
>         "DeleteDate": null

https://github.com/FiltersHeroes/KAD/commit/748d6eafb6297265b13828574d0f4073542e7c33#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R19170

**Comment by krystian3w** [comment]
Offilne, wypadła z bazy WHOIS.

**Comment by hawkeye116477** [comment]
W zasadzie to nie wypadła z bazy, jest zawieszona.
