### ISSUE TITLE
drugiewydanie.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2053]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
drugiewydanie.pl
```

### Dodatkowe informacje mogące mieć znaczenie

https://twitter.com/CeneoPL/status/1489514757891764224

**Comment by ClusterByte-x** [comment]
https://www.ceneo.pl/sklepy/drugiewydanie.pl-s32328
https://twojeopinie.com/drugie-wydanie
