### ISSUE TITLE
joedohn.site

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2061]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://www.joedohn.site/przelewy24/trnRequest/DB3D9963A9/
```

### Dodatkowe informacje mogące mieć znaczenie

Blik `DO ODBIORU: 500 zł Wprowadź swój numer telefonu aby przejść do odbioru środków`

Tak zgłaszałem to do Cert i to nawet wczoraj i cisza.

**Comment by krystian3w** [comment]
Najpewniej ID jest przypisane do IP: DB3D9963A9
