### ISSUE TITLE
frog.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2063]
### Dodatkowe informacje mogące mieć znaczenie
Podejrzany sklep. Prośba o analizę.
https://www.wykop.pl/wpis/63851065/ktos-wie-czy-to-jest-legitny-sklep-frog-pl-mam-zam/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Plakat wymienili:

![obraz](https://user-images.githubusercontent.com/35370833/155017856-e07f13ce-8de6-4ee7-9f7e-1cf2257b1c66.png)


 opinie Google 5.0 ⭐ ⭐ ⭐ ⭐ ⭐:

![obraz](https://user-images.githubusercontent.com/35370833/155017733-c93bb6f6-7148-448e-8243-7095cb98f4d7.png)

Podobnie na ceneo:

https://www.ceneo.pl/sklepy/frog.pl-s26311

Nie oszukiwał przez ostatni rok z pomocą konta Allegro.
