### ISSUE TITLE
vabkal.com.ua

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2064]
### Link bezpośredni 

    https://vabkal.com.ua/?subid3=www.onet.pl&gclid=EAIaIQobChMIsJXfuOeV9gIVTVzlCh1AYwYmEAEYASAAEgLWVfD_BwE

### Dodatkowe informacje mogące mieć znaczenie
Jakas nowa odmiana, znaleziona na reklamie na onecie. Chyba sprawdza refer bo bezposrednie wejscie na `https://vabkal.com.ua` pokazuje kosmetyki. Nizej link ktory jest na onecie i kieruje do scamu.

```
https://vabkal.com.ua/?subid3=www.onet.pl&gclid=EAIaIQobChMIsJXfuOeV9gIVTVzlCh1AYwYmEAEYASAAEgLWVfD_BwE

https://adclick.g.doubleclick.net/aclk?sa=l&ai=CrXHEHSYWYvCSH824lQfAxpmwApz8371o6bSotdcPv-EeEAEgt-WEIWDpBKABsoH9pCjIAQmpAlhtTbZSJ0s-qAMByAPLBKoExwFP0CHVnCqdkKcTTgOrJv9cDM5ErlOTqeXmjSAzqhiF5i4jGZ6QH_vUVj5iMKcnD-UIdRBx4NRBwA5B-gD8ITypWDXdiS_In5LK4egCwOoKeSp7SFqs5i8jGVCTfZLd4MBV3xo81skSIr7PETPo3NU1aCUJYVqlFwGsYHyWSiJ5b5XxoU-uaFINYiA0IUkPp9wcsp8jKFXHL9uYG3f8SZE2zmCuS0SYWpQc5ImUWSMOZOpxIH2o9q_oK696CDWnspQHUER84i2qwATCtvCP7wOgBi6AB7K5zYQDqAeOzhuoB5PYG6gH7paxAqgH_p6xAqgH1ckbqAemvhuoB_PRG6gHltgbqAeqm7ECqAffn7EC2AcA0ggJCIDhgBAQARgA8ggNYmlkZGVyLTIzOTk0MrEJs5H2v1C2NhiACgSYCwHICwGADAG4DAGIFAHQFQH4FgGAFwE&ae=1&num=1&pr=13:YhYmHQAAAAACqyGm_s_0442jpqJqxQ7v34vzjg&sig=AOD64_2toxQp0kQ6-db7EOwIZUOl-Gnbtw&client=ca-pub-5722610347565274&nb=9&adurl=https://vabkal.com.ua/%3Fsubid3%3Dwww.onet.pl%26gclid%3DEAIaIQobChMIsJXfuOeV9gIVTVzlCh1AYwYmEAEYASAAEgLWVfD_BwE
```
Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
Ja tam widzę tylko kosmetyki.

**Comment by krystian3w** [comment]
Trzeba chamsko wymusić refferer na Google/Onet.

Nie wiem czy NASK ogarnie - raczej nie ;(

**Comment by krystian3w** [comment]
![Screenshot_20220223-145506_Firefox](https://user-images.githubusercontent.com/35370833/155333226-02150c65-f968-46ba-a119-248363c00122.jpg)
