### ISSUE TITLE
Ukraina o atakach phishingowych, są też polskie domeny

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#2066]
### Link bezpośredni do strony zawierającej źródło 

```markdown
https://sekurak.pl/ukraina-poinformowala-o-atakach-phishingowych-na-swoich-zolnierzy-zobaczcie-tez-polskie-domeny/
```

### Dodatkowe informacje mogące mieć znaczenie

```
account-inbox.online

account-logins.online

accounts-login.online

accounts-telekom.online

akademia-mil.space

authorization-inbox.site

com-account.website

com-firewall.online

com-validate.site

com-verify.site

command-email.online

credentials-telekom.online

creditals-mirohost.space

i-ua.site

i.ua-passport.space

id.bigmir.space

inbox-admin.site

interia-firewall.site

interia-pl.website

interia.kontrola-bezpieczenstwa.space

interia.sprawdzanie-konta.space

is-lt.online

konto-verify.space

konto.weryfikacja-uzytkownika.space

kontrola-bezpieczenstwa.online

kontrola-bezpieczenstwa.site

kontrola-bezpieczenstwa.space

kontrola-bezpieczenstwa.website

kontrola-poczty.site

kontrola-poczty.space

login-inbox.online

login-inbox.site

login-mail.online

login-microsoftonline.site

login-telekom.online

login-verify.online

login-yahoo.site

login.walidacja-poczty.space

logowanie-pl.site

mail-validation.online

meta-ua.online

mil-secure.site

mirohost-creditals.space

mirohost.online

mirohost.site

mod-mil.online

mod-mil.site

net-account.online

net-account.space

net-firewall.online

net-support.site

net-verification.online

net-verify.site

net-verify.website

onet-pl.online

op-pl.site

pis.kontrola-bezpieczenstwa.site

pis.kontrola-bezpieczenstwa.website

poczta.kontrola-bezpieczenstwa.site

poczta.kontrola-bezpieczenstwa.website

potwierdzenie.site

ron-mil-pl.space

ron-mil.space

ru-mailbox.site

ru-passport.online

safe-control.space

safe-onet.online

safe-onet.space

secure-firewall.site

secure-firewall.website

secure-ua.site

secure-ua.website

sign-in-inbox.site

signin-inbox.online

signin-telekom.online

sprawdzanie-konta.space

sprawdzanie-poczty.space

telekom-dienste.online

ua-agreements.online

ua-login.site

ua-passport.online

ua-passport.site

ukroboronprom-com.site

ukroboronprom.online

verify-ua.online

verify-ua.site

verify-ua.space

walidacja-konta.space

walidacja-poczty.space

walidacja-uzytkownika.online

walidacja-uzytkownika.site

walidacja-uzytkownika.space

walidacja-uzytkownika.website

weryfikacja-konta.space

weryfikacja-poczty.space

weryfikacja-uzytkownika.site

weryfikacja-uzytkownika.space

weryfikacja-uzytkownika.website

wirtualna-polska.online

wp-agreements.online

wp-firewall.website

wp-pl-potwierdz-dostep.site

wp-potwierdzac.site
```

**Comment by krystian3w** [comment]
| subdomena | domena                  | tld     | ip             |
|----------:|:------------------------|:--------|:--------------:|
|           | account-inbox           | online  | 208.91.197.91  |
|           | account-logins          | online  | Not found      |
|           | accounts-login          | online  | Not found      |
|           | accounts-telekom        | online  | Not found      |
|           | akademia-mil            | space   | Not found      |
|           | authorization-inbox     | site    | Not found      |
| id        | bigmir                  | space   | Not found      |
|           | com-account             | website | Not found      |
|           | com-firewall            | online  | Not found      |
|           | com-validate            | site    | Not found      |
|           | com-verify              | site    | 104.21.17.78   |
|           | command-email           | online  | 104.21.44.2    |
|           | credentials-telekom     | online  | Not found      |
|           | creditals-mirohost      | space   | 172.67.178.184 |
|           | i-ua                    | site    | Not found      |
|           | inbox-admin             | site    | Not found      |
|           | interia-firewall        | site    | 208.91.197.91  |
|           | interia-pl              | website | Not found      |
|           | is-lt                   | online  | Not found      |
|           | konto-verify            | space   | Not found      |
|           | kontrola-bezpieczenstwa | online  | Not found      |
|           | kontrola-bezpieczenstwa | site    | Not found      |
|           | kontrola-bezpieczenstwa | space   | Not found      |
|           | kontrola-bezpieczenstwa | website | Not found      |
| pis       | kontrola-bezpieczenstwa | site    | Not found      |
| poczta    | kontrola-bezpieczenstwa | site    | Not found      |
| interia   | kontrola-bezpieczenstwa | space   | Not found      |
| pis       | kontrola-bezpieczenstwa | website | Not found      |
| poczta    | kontrola-bezpieczenstwa | website | Not found      |
|           | kontrola-poczty         | site    | 208.91.197.91  |
|           | kontrola-poczty         | space   | Not found      |
|           | login-inbox             | online  | Not found      |
|           | login-inbox             | site    | Not found      |
|           | login-mail              | online  | Not found      |
|           | login-microsoftonline   | site    | Not found      |
|           | login-telekom           | online  | Not found      |
|           | login-verify            | online  | Not found      |
|           | login-yahoo             | site    | Not found      |
|           | logowanie-pl            | site    | Not found      |
|           | mail-validation         | online  | Not found      |
|           | meta-ua                 | online  | Not found      |
|           | mil-secure              | site    | 194.195.211.26 |
|           | mirohost                | online  | 208.91.197.91  |
|           | mirohost                | site    | 208.91.197.91  |
|           | mirohost-creditals      | space   | Not found      |
|           | mod-mil                 | online  | 208.91.197.91  |
|           | mod-mil                 | site    | 208.91.197.91  |
|           | net-account             | online  | Not found      |
|           | net-account             | space   | Not found      |
|           | net-firewall            | online  | 104.21.94.3    |
|           | net-support             | site    | Not found      |
|           | net-verification        | online  | Not found      |
|           | net-verify              | site    | Not found      |
|           | net-verify              | website | Not found      |
|           | onet-pl                 | online  | Not found      |
|           | op-pl                   | site    | 194.195.211.26 |
|           | potwierdzenie           | site    | Not found      |
|           | ron-mil                 | space   | Not found      |
|           | ron-mil-pl              | space   | Not found      |
|           | ru-mailbox              | site    | Not found      |
|           | ru-passport             | online  | Not found      |
|           | safe-control            | space   | Not found      |
|           | safe-onet               | space   | 172.67.131.198 |
|           | safe-onet               | online  | Not found      |
|           | secure-firewall         | site    | Not found      |
|           | secure-firewall         | website | Not found      |
|           | secure-ua               | site    | Not found      |
|           | secure-ua               | website | Not found      |
|           | sign-in-inbox           | site    | Not found      |
|           | signin-inbox            | online  | Not found      |
|           | signin-telekom          | online  | Not found      |
|           | sprawdzanie-konta       | space   | Not found      |
| interia   | sprawdzanie-konta       | space   | Not found      |
|           | sprawdzanie-poczty      | space   | Not found      |
|           | telekom-dienste         | online  | 172.67.166.129 |
|           | ua-agreements           | online  | 172.67.213.97  |
|           | ua-login                | site    | Not found      |
|           | ua-passport             | online  | Not found      |
|           | ua-passport             | site    | Not found      |
| i         | ua-passport             | space   | Not found      |
|           | ukroboronprom           | online  | Not found      |
|           | ukroboronprom-com       | site    | Not found      |
|           | verify-ua               | online  | Not found      |
|           | verify-ua               | site    | Not found      |
|           | verify-ua               | space   | Not found      |
|           | walidacja-konta         | space   | Not found      |
|           | walidacja-poczty        | space   | Not found      |
| login     | walidacja-poczty        | space   | Not found      |
|           | walidacja-uzytkownika   | site    | 104.21.21.142  |
|           | walidacja-uzytkownika   | online  | Not found      |
|           | walidacja-uzytkownika   | space   | Not found      |
|           | walidacja-uzytkownika   | website | Not found      |
|           | weryfikacja-konta       | space   | Not found      |
|           | weryfikacja-poczty      | space   | Not found      |
|           | weryfikacja-uzytkownika | site    | 172.67.152.63  |
|           | weryfikacja-uzytkownika | space   | Not found      |
|           | weryfikacja-uzytkownika | website | Not found      |
| konto     | weryfikacja-uzytkownika | space   | Not found      |
|           | wirtualna-polska        | online  | Not found      |
|           | wp-agreements           | online  | 172.67.177.41  |
|           | wp-firewall             | website | Not found      |
|           | wp-pl-potwierdz-dostep  | site    | Not found      |
|           | wp-potwierdzac          | site    | Not found      |

[lista.csv](https://github.com/FiltersHeroes/KAD/files/8156083/txt.csv)

Duża część offline, część dziwacznie pobanował CERT np. znają subdomeny jakich raport republikowany na seurak.pl nie wykrył.
