### ISSUE TITLE
foresig-market.biz

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#2072]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://foresig-market.biz/Holow_new/
```

### Dodatkowe informacje mogące mieć znaczenie

fake

**Comment by krystian3w** [comment]
Częściowo zbanowane: https://github.com/FiltersHeroes/KAD/blob/7cf4b6ec4f8c3381b153f0529e2f018174f0d1d6/sections/przekierowujace_do_przekretow.txt#L134

**Comment by krystian3w** [comment]
Cert do bana się nie kwapi.
