### ISSUE TITLE
www.dsnpj.shop

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#2076]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://www.dsnpj.shop
```

### Dodatkowe informacje mogące mieć znaczenie

fake sklep

**Comment by hawkeye116477** [comment]
@krystian3w Łapka w górę nie sprawi, że samo się doda :stuck_out_tongue:

**Comment by krystian3w** [comment]
Jeszcze było 43 minut zapasu.
