### ISSUE TITLE
tickets.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2078]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
tickets.pl
```

### Dodatkowe informacje mogące mieć znaczenie

Takie coś znalazłem
https://pl.trustpilot.com/review/tickets.pl
https://niezaleznaopinia.pl/wakacje-podroze/tickets-recenzje
https://www.google.com/search?q=tickets.pl&oq=tickets.pl&ie=UTF-8#lrd=0x471ecc8de1549fd3:0xb0daf336a0ea2de9,1,,,

**Comment by ClusterByte-x** [comment]
<img width="851" alt="Zrzut ekranu 2022-03-14 o 21 59 49" src="https://user-images.githubusercontent.com/76107417/158260497-241083c5-29a5-47bd-8b70-ac11406d6991.png">
