### ISSUE TITLE
systemrma.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2094]
### Link bezpośredni 
`https://systemrma.pl`
### Dodatkowe informacje mogące mieć znaczenie
Strona jest zablokowana, a chyba nie powinna być? Przykładowo sklep bitcomputer.pl korzysta z tego systemu do gwarancji teraz i zajęło mi chwilę ogarnięcie dlaczego strona się nie wczytuje i co ją blokuje, niestety w sekcji Issues na GitHubie nie widzę tego w historii...

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Domenę im zhakowano/zanifekowano: #1346

Więc najpewniej pora na full revert commitu z tamtego issue.
