### ISSUE TITLE
Net-s.pl - niesłusznie zablokowany

### ISSUE THREAD

**Issue by the4anoni** [FiltersHeroes/KAD#2100]
### Bloker (Blocker)

AdGuard Nightly

### Link bezpośredni, na którym występuje problem

```markdown
net-s.pl
```

### Opis błędu

Net-s.pl to nie jest oszustwo, tylko zwyczajny sklep internetowy.
`||net-s.pl^$document,popup`

### Dodatkowe informacje mogące mieć znaczenie

![Screenshot_20220429-063739_Vivaldi Browser](https://user-images.githubusercontent.com/13403084/165885848-a1a4204f-9fca-45d5-a74e-bdd65467b88c.png) | ![Screenshot_20220429-063804_AdGuard](https://user-images.githubusercontent.com/13403084/165885869-4d4adf7b-9a5e-44f0-b198-77ba2fc287c2.png)
--- | ---

**Comment by hawkeye116477** [comment]
Zdania są podzielone, sprawa kontrowersyjna...

https://github.com/FiltersHeroes/KAD/issues/2023

**Comment by ClusterByte-x** [comment]
https://www.wykop.pl/link/6650357/sklep-internetowy-net-s-oszusci-wyludzenie/najnowsze/
