### ISSUE TITLE
www.indaajach.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2103]
### Link bezpośredni 
`https://www.indaajach.com/index.php?main_page=shippinginfo_add`
### Dodatkowe informacje mogące mieć znaczenie
oszustwo: strona jest lewa, uwaga!!!

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Zablokowane, proszę zaktualizować listę.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/commit/51551a7c36a08554f1b9f2038edf432ef93cdb86#diff-5c51b251c292f5c5855613f3392f09f1f52a958a53930a32dfa6e3d0529c8151R905

**Comment by krystian3w** [comment]
`www.` dla hosts i pi-hole jest doklejane:

> https://github.com/FiltersHeroes/KADhosts/commit/0c5112ec74d78c3ca2985e77a775ed00ba955b48#diff-0cb6b2b322378cb88a5ef38147d3fea603a48615f505e9cae7d5eaf18bf6a603R923
https://github.com/FiltersHeroes/KADhosts/commit/0c5112ec74d78c3ca2985e77a775ed00ba955b48#diff-0cb6b2b322378cb88a5ef38147d3fea603a48615f505e9cae7d5eaf18bf6a603R3037


> https://github.com/FiltersHeroes/KADhosts/commit/a679fc4d6aee22f8b97ceb873223abebe20a82e0#diff-10176db289275d94cf4db522d31673a57737d93d9b779e3c2edb5c151545c770R3036 ​​​​​​https://github.com/FiltersHeroes/KADhosts/commit/a679fc4d6aee22f8b97ceb873223abebe20a82e0#diff-10176db289275d94cf4db522d31673a57737d93d9b779e3c2edb5c151545c770R922
