### ISSUE TITLE
wind-media.net

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2107]
### Link bezpośredni 
`https://newweb.windmedia88.com/`
`https://newweb.windmedia88.com/#/login`
### Dodatkowe informacje mogące mieć znaczenie
`https://www.wykop.pl/wpis/64100479/ej-mirki-co-to-za-scam-xd-uposledzony-znajomy-mi-w/`

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
@krystian3w `pl.wind-media.net` jest po polsku
