### ISSUE TITLE
bypasscard.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2117]
### Link bezpośredni 
`https://dev-com.sc`
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/66005367/zalozylem-konto-na-vited-pl-i-jakies-dziwne-ruchy-/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Strona od razu przekierowuje na rosyjskojęzyczne coś (ukraiński serwer "pracuje" a nie "robotet").
