### ISSUE TITLE
haradso.host

### ISSUE THREAD

**Issue by FadeMind** [FiltersHeroes/KAD#2121]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://haradso.host/poczta/8923057/982357/
```

### Dodatkowe informacje mogące mieć znaczenie

Inpost scam z bramką płatności. ESET blokuje, ale Google, czy KAD nie. Dostałem SMS z linkiem i chciałem sprawdzić czy blokujecie (obecnie nie). 

Na marginesie

![20220619-1655624892](https://user-images.githubusercontent.com/9846948/174471100-d1d82cfd-1ce4-4354-9737-0d6b2f2c37d6.png)

**Comment by xMaap** [comment]
Już blokuje.

**Comment by krystian3w** [comment]
```json
    {
        "RegisterPositionId": 59052,
        "DomainAddress": "www.haradso.host",
        "InsertDate": "2022-06-19T09:21:30",
        "DeleteDate": null
    },
    {
        "RegisterPositionId": 59051,
        "DomainAddress": "haradso.host",
        "InsertDate": "2022-06-19T09:21:25",
        "DeleteDate": null
    },
```
