### ISSUE TITLE
allegra-pl.net

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2127]
### Link bezpośredni 
`https://allegra-pl.net/78569/`
### Dodatkowe informacje mogące mieć znaczenie
Strona phishingowa rozsyłana poprzez SMS próbująca wyłudzić dane logowania do allegro.pl

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Cert zabanował: https://github.com/FiltersHeroes/KAD/commit/6c5ebb8452c10a414cac8538896d802410ce08f0

Zgłoszenia nie wymuszą wprowadzenia więcej niż 4 cyklów sprawdzania nowości z LWS i CERT-u.
