### ISSUE TITLE
anuluj-dlug.pl i anuluj-mandat.pl źle oznaczone jako kad (przekręt)

### ISSUE THREAD

**Issue by PatrykMis** [FiltersHeroes/KAD#2131]
### Bloker (Blocker)

uBlock Origin (wszystkie obsługujące ten filtr)

### Link bezpośredni, na którym występuje problem

```markdown
https://anuluj-dlug.pl/
```

### Opis błędu

Jest to kancelaria direct skupiająca prawników (adwokatów, radców prawnych) pomagających anulować niezasadne długi w Sądzie. Najpierw skorzystała moja przyjaciółka, potem ja - i ponad wszelką wątpliwość deklaruję, że ten adres, jak również anuluj-mandad.pl powinny bezprecedensowo zniknąć z tej listy i nigdy się tam więcej nie pojawić.
Żadna ściema, żaden przekręt.

### Dodatkowe informacje mogące mieć znaczenie

Jeśli potrzeba udzielę bliższych informacji nawet prywatnie.

**Comment by hawkeye116477** [comment]
```
https://github.com/FiltersHeroes/KAD/issues/343
https://github.com/FiltersHeroes/KAD/issues/344
https://www.forum-kredytowe.pl/t/94647-czy-ktos-korzystal-z-anuluj-dlug/
```

**Comment by PatrykMis** [comment]
Przejrzałem githubowe "issues" i wątek na forum-kredytowe. W wypadku obu issues każdy z nich nie posiada żadnego uzasadnienia. Co do reszty i wątku na forum:

1. Żeby zrozumieć o co chodzi, warto zaufać realnym nazwiskom i realnie istniejącym osobom, niż nickom na forum, gdzie praktyką powszechną są multikonta i gra konkurencji.
2. Realną osobą jestem chociażby ja, który z imienia i nazwiska (oraz swoich pull requestów/commitów) się nie ukrywam, a także Tomasz Parol, założyciel i fundator fundacji Angeli Iustitia oraz fundacji Trucker będącej w posiadaniu obu domen.
3. Istnieje obszerny materiał dowodowy w postaci publikowanych wyroków, wpisów na blogu (niegdyś bardzo regularnych), będący nie tylko namacalnym dowodem, ale przede wszystkim źródłem wiedzy, w jaki sposób działa oraz na czym opiera się działalność fundacji i ich pomoc. Anuluj-dlug czy anuluj-mandat.pl to nie tylko sam portal, ale również social media - np. [filmy na kanale youtube](https://www.youtube.com/channel/UCIOqbRSm_IhB51b814mR5xQ/videos). Oczywiście każda strona ma swój kanał czy stronę na Facebook, i bez względu na datę dodania filmów warto je po prostu obejrzeć.
4. Bardzo wielu ludzi nie pochwali się publicznie ich (kancelarii) sukcesami – czy to przez wiek i "nieogarnianie" spraw komputerowych, inne niepełnosprawności, czy - po prostu - normalnym jest, że ludzie nie chcą się zazwyczaj publicznie chwalić tym, w jakie "bagno" finansowe w taki czy inny sposób wpadli. Ja też jestem osobą niepełnosprawną i też wolałbym pewne rzeczy przemilczeć, ale mam taką naturę, że będę walczył o prawdę - bo i na swoim i na mojej znajomej przypadku wiem, że fachowo i profesjonalnie podeszli do tematu.

Reasumując: blokowanie strony w oparciu o domniemania będące konkluzją wpisów fikcyjnych kont to zbyt rygorystyczne i krzywdzące podejście.

**Comment by krystian3w** [comment]
W sumie może zwolnili starą kadrę co rozpatrywała sprawę zbyt długo lub łamała "RODO" wydając pisma z błędnymi danymi osobowymi innego klienta - tu raczej musiał zadziałać wilczy bilet zamiast bronić swojego pracownika.
