### ISSUE TITLE
cqwnqk.top

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2141]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/66523079/panowie-mamy-przesrane-skamerzy-wzieli-sie-za-elon/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Homepage wydaje się być czyste, więc domena musi wykrywać np. refferer Facebooka lub działa z jakiegoś katalogu lub z dziwnymi parametrami.
