### ISSUE TITLE
emaqinin.tk

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2149]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://emaqinin.tk/ball/paycard/index.php
```

### Dodatkowe informacje mogące mieć znaczenie

Płatność Orange

**Comment by krystian3w** [comment]
> `Witryny potwierdzają swoją tożsamość poprzez certyfikaty. Firefox Developer Edition nie ufa certyfikatowi witryny „emaqinin.tk”, ponieważ nie jest on dla niej prawidłowy. Ten certyfikat jest prawidłowy tylko dla domeny cert.t-mobile.pl.Witryny potwierdzają swoją tożsamość poprzez certyfikaty. Firefox Developer Edition nie ufa certyfikatowi witryny „emaqinin.tk”, ponieważ nie jest on dla niej prawidłowy. Ten certyfikat jest prawidłowy tylko dla domeny cert.t-mobile.pl.`

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/commit/9586aa1bcec64dab1f5dfe1cb331e416542a6b31#diff-50722a3325584da687dc35a97b54ebb75db04e85da0e2531ab48492752fbec64R8910
