### ISSUE TITLE
opalekogroszek.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2150]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/66765921/witam-mireczki-i-mirabelki-moj-stary-znalazl-stron/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
https://www.google.com/search?q=klient.baselinker.com%2F436571470%2Fhpitb8wf14%2F
