### ISSUE TITLE
pol.braopolis.com

### ISSUE THREAD

**Issue by mino815** [FiltersHeroes/KAD#2151]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://pol.braopolis.com/?ptnwfkeh44038
```

### Dodatkowe informacje mogące mieć znaczenie

Strona z fake newsem wyłudzająca login i hasło do Facebooka:

![292965873_522513589673831_898201442230299212_n](https://user-images.githubusercontent.com/47322804/180570590-e3b1afe1-a0b2-4bd8-9e30-c229f0768448.png) |
--- |

**Comment by krystian3w** [comment]
Możesz próbować takie coś zgłaszać jako phishing: https://incydent.cert.pl/phishing

Jak CERT uzna to za zagrożenie, to bot doda przy najbliższym cyklu pobierania nowości z projektu i LWS (legalnie w sieci - podejrzane sklepy WWW).

**Comment by xMaap** [comment]
Tam też jest inny scam
`https://pl2.xfreepresent.com/start_247.html
`![Screenshot_20220723_015651](https://user-images.githubusercontent.com/36385327/180581762-6d7967f8-bf30-43bb-adf4-4b09d0de82bc.png)

**Comment by krystian3w** [comment]
Mnie tamten wyskoczył z ankiet.
