### ISSUE TITLE
ferteks.co.uk

### ISSUE THREAD

**Issue by mino815** [FiltersHeroes/KAD#2152]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://ferteks.co.uk/
```

### Dodatkowe informacje mogące mieć znaczenie

Domena ma kilka dni, brak jakichkolwiek profili czy opinii na Facebooku lub Trustpilot. Wygląda na scam.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/discussions/1946
