### ISSUE TITLE
weglokokskraj-sklep.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2159]
### Dodatkowe informacje mogące mieć znaczenie
https://www.wykop.pl/wpis/66942757/informacyjnie-tylko-mirasy-nie-dajcie-sie-zrobic-w/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Only one step left!
To finish setting up your new web address, go to [your domain settings](https://www.shopify.com/admin/settings/domains), click "Connect existing domain", and enter: weglokokskraj-sklep.pl
