### ISSUE TITLE
merlin.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2164]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
merlin.pl
```

### Dodatkowe informacje mogące mieć znaczenie

Nie wiem czy się nadaje, ale od 2020 mają problemy:
- https://www.bankier.pl/wiadomosc/Na-zwrot-pieniedzy-czekam-od-stycznia-UOKiK-bierze-pod-lupe-sklep-merlin-pl-8387998.html
- https://www.ceneo.pl/sklepy/merlin.pl-s4436

**Comment by krystian3w** [comment]
Już było przez około miesiąc: https://github.com/FiltersHeroes/KAD/issues/1341

Jakby był wniosek o upadłość, to można by jak sowę traktować #1512

**Comment by Lukjan39** [comment]
nie jest oszustwem, tylko polaczyli sie z kilkoma ksiegarniami.

prosze zmienic w filtrach.

**Comment by hawkeye116477** [comment]
Rozumiem, że kupowałeś tam ostatnio. Bo jednak ja widzę negatywne opinie na paru stronach, tak samo jak i w artykule z Money.

**Comment by Lukjan39** [comment]
ostatnio rok temu, przed polaczeniem stron

**Comment by krystian3w** [comment]
Można zmienić siłę z `all` na `doc` (AdGuard niby już naprawił, że nie tylka to xmlhttprequestów).

**Comment by Lukjan39** [comment]
dodalem juz do mojej listy w ublock origin

**Comment by Lukjan39** [comment]
o co chodzi?

**Comment by krystian3w** [comment]
21 wisiało otwarte, to zamykamy.

**Comment by Lukjan39** [comment]
aha, dobra
