### ISSUE TITLE
zonelatreal.netlify.app

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2167]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
zonelatreal.netlify.app
```

### Dodatkowe informacje mogące mieć znaczenie

![Screenshot_20220818_215150](https://user-images.githubusercontent.com/36385327/185482575-6e73e4e9-68c0-47b5-8d29-cff665a33baa.png)

**Comment by krystian3w** [comment]
https://answers.netlify.com/t/report-abuse-for-a-netlify-site/22905/3

**Comment by krystian3w** [comment]
Strona zdjęta wraz z kontem "netlify".
