### ISSUE TITLE
onczolat.netlify.app

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2169]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
onczolat.netlify.app
```

### Dodatkowe informacje mogące mieć znaczenie

Akcje Orlen to samo co https://github.com/FiltersHeroes/KAD/issues/2165 https://github.com/FiltersHeroes/KAD/issues/2167

**Comment by krystian3w** [comment]
Padło lub netlify zbanowały

**Comment by krystian3w** [comment]
https://answers.netlify.com/t/report-abuse-for-a-netlify-site/22905/3
