### ISSUE TITLE
`finger-offers.com` na `*.netlify.app`

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2176]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
ukonret.netlify.app - zbanowane
```

### Dodatkowe informacje mogące mieć znaczenie

![Screenshot_20220823_195254](https://user-images.githubusercontent.com/36385327/186229872-27a9cefb-0f9d-4185-a514-a80794302068.png)

**Comment by krystian3w** [comment]
Wysłałem prośbę o bana w netlify.

**Comment by xMaap** [comment]
Kolejne
`mastruir.netlify.app`

**Comment by xMaap** [comment]
`ukonasz.netlify.app`

**Comment by xMaap** [comment]
`akcjetren.netlify.app`
