### ISSUE TITLE
docs.google.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2181]
### Link bezpośredni 
`https://docs.google.com/forms/d/e/1FAIpQLSfrpNtBRCOz39pSFFq1GavuIKS8K6lmrJzOhOPcAmYR8af2zg/viewform`
### Dodatkowe informacje mogące mieć znaczenie
Wyłudzanie danych poprzez form. Google.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@hawkeye116477 jakiś bug z mailem

**Comment by hawkeye116477** [comment]
@krystian3w Żaden błąd, po prostu zgłaszający wpisał maila do pola tytuł.
