### ISSUE TITLE
Enable syntax highlight

### ISSUE THREAD

**Issue by scripthunter7** [FiltersHeroes/KAD#2187]
Hello!

GitHub now supports syntax highlighting of adblock filter lists, but this requires the presence of the adblock agent. Demo: https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/test_rules.txt

If you want to enable it, just insert the appropriate agent at the beginning of your [filters](https://github.com/FiltersHeroes/KAD/blob/master/KAD.txt). For example `[Adblock Plus 2.0]`

**Comment by krystian3w** [comment]
Deleted to disable list in AdBlock and AdBlock Plus and his family, fyi @hawkeye116477.

https://github.com/FiltersHeroes/KAD/commit/70d21059c5472d8dad553b201e1244e04561be4c

Highlight maybe useful in section files used to built main file:

https://github.com/FiltersHeroes/KAD/tree/master/sections

If FOP support extension ".adblock" - name need check to avoid generic block by EasyList if someone break settings in trusted domains for uBo (AdBlock, ABP and AdGuard maybe don't touch downloaded files by exist network filters).

**Comment by scripthunter7** [comment]
You can even use the `.gitattributes` file. Example: https://github.com/AdguardTeam/AdguardFilters/blob/master/.gitattributes

**Comment by scripthunter7** [comment]
@krystian3w you can also highlight other files with this method
