### ISSUE TITLE
Domeny `natural.pl`

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2190]
### Link bezpośredni 
`https://natural.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Dzień dobry. Domena nie jest już niebezpieczna, bardzo prosimy o usunięcie jej z listy :)

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Pewnie chodzi o witaminę D3 lub kwas Omega.

**Comment by krystian3w** [comment]
Nie widać by sytuacja się poprawiła a są już nawet skargi od południowych sąsiadów (Czechy, Słowacja, Węgry).
