### ISSUE TITLE
szukam-pracy.waw.pl

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2192]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
szukam-pracy.waw.pl
```

### Dodatkowe informacje mogące mieć znaczenie

Logowanie do Facebooka
https://cert.orange.pl/aktualnosci/szukasz-pracy-tracisz-konto-na-facebooku

**Comment by krystian3w** [comment]
Ban NASK.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/commit/1403c9aa2c4bb39b9774d51de5dffde282c7a18a#diff-50722a3325584da687dc35a97b54ebb75db04e85da0e2531ab48492752fbec64R24447
