### ISSUE TITLE
wuinso.site

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2193]
### Link bezpośredni 
`https://tiny.one/yrb6fc` aka `https://wuinso.site/pl/pge/87315823/1895292/`
### Dodatkowe informacje mogące mieć znaczenie
Oszustwo. "PGE: Na dzien 12.09.2022 zaplanowano odlaczenie energii elektrycznej! Prosimy o uregulowanie naleznosci: `https://tiny.one/yrb6fc`"

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie blokujemy skróconych linków, zgłosić możesz do platformy spamowy link.
