### ISSUE TITLE
maschinen.ba

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2198]
### Link bezpośredni 
`http://up.maschinen.ba/`
### Dodatkowe informacje mogące mieć znaczenie
Wyłudzanie danych do logowania do systemu pocztowego.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
@krystian3w Wkradł się tam `.com` nie powinno tam go być https://github.com/FiltersHeroes/KAD/commit/2453b377bde21a57ed704ca70a40ff98f8548808#diff-b48172f5abba059715bc4c533fa252462fde8dc7943aa74b2dbfdeadc91cb280R1
