### ISSUE TITLE
zalukaj.ru

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2199]
### Dodatkowe informacje mogące mieć znaczenie
Prosiłbym o odblokowanie zalukaj.ru tak jak zalukaj.vip ponieważ tutaj da się normalnie oglądać.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Na VIP dalej jest limit i potem wykup pakietów w ciemno (niby trzeba coś do adminów napisać).
