### ISSUE TITLE
bikdor-invest.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2202]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://bikdor-invest.com
```

### Dodatkowe informacje mogące mieć znaczenie

![FdaAa4vX0AUinw1](https://user-images.githubusercontent.com/36385327/192088786-a4f91922-631c-4aef-8872-90a3073c23be.jpg)
https://twitter.com/Sekurak/status/1573586482228494339

**Comment by krystian3w** [comment]
Czemu nie zgłosili by zdjąć reklamę?
