### ISSUE TITLE
Niepoprawna reguła

### ISSUE THREAD

**Issue by F4z** [FiltersHeroes/KAD#221]
Cześć, moim zdaniem ta reguła (https://github.com/azet12/KAD/blob/master/KAD.txt#L1658)
`||alltube.tv###ban-er` jest niepoprawna i powinna wyglądać tak - `alltube.tv###ban-er`
Chodzi o te dwie kreski pionowe na początku reguły `||`, one powodują, że reguła nie działa.

**Comment by azet12** [comment]
Zgadza się, jednak po niedawnej aktualizacji wyglądu alltube chyba już nawet nie ma czegoś takiego, przynajmniej na to wygląda bo nie widze różnicy z włączoną i wyłączoną regułą. Czy u Ciebie jest tak samo?

**Comment by F4z** [comment]
Masz rację, ja również nie mogę znaleźć takiego elementu na stronie.

**Comment by azet12** [comment]
Ok, usuwam. Dzięki

**Comment by krystian3w** [comment]
Wszystkie 3 warianty mają przekierowanie na: https://www.alliance4creativity.com/watch-it-legally/
