### ISSUE TITLE
u29570188.ct.sendgrid.net - new phishing domain

### ISSUE THREAD

**Issue by kioan** [FiltersHeroes/KAD#2217]
u29570188.ct.sendgrid.net is also a phishing domain.
Right now it is running a campaign which targets Greek users by pretending to be the official postal office.

**Comment by kioan** [comment]
I thought it would be useful to report this domain to you, because I've noticed that your list includes multiple *.ct.sendgrid.net subdomains. Malicious domains are frequently used for hosting attacks targeting users from multiple countries.

I am using your list in the networks I administer, through the unified lists that [StevenBlack](https://github.com/StevenBlack/hosts) publishes.

**Comment by krystian3w** [comment]
I think 99-100% was form https://hole.cert.pl/domains/

Then maybe Polish CERT block in Poland this Greek Phishing but his guys also needed direct URL to confirm Phishing if is still active.

Rather, not every page from that project should be checked if it is in Polish (Especially when it uses a strange directory or link parameters - which CERT does not have provide to share).

**Comment by ClusterByte-x** [comment]
Hello!

The site doesn’t qualify as KAD filters - not include Polish localization.

The site was submitted to the relevant CERT organizations (Poland, Greece) and several anti-virus vendors. At the moment the site appears to have been disabled (404).

**Comment by kioan** [comment]
The phishing site is now removed. The link I had does not work any more.

I think that this issue should be closed. Thank you for all your replies.
