### ISSUE TITLE
novaconcept-wroclaw.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2220]
### Link bezpośredni 
`http://novaconcept-wroclaw.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Strona została zawirusowana co spowodowało wysyłanie spamu. Pliki witryny zostały usunięte i zależy nam na samej skrzynce pocztowej. Prosimy o usunięcie naszego adresu ze spisu witryn.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Strona jest zbanowana przez CERT i fundację Mozilla.

Czyli nasze odblokowanie niewiele da jak CERT i Mozilla strzelą focha na wasze usunięcie infekcji phishingowej.

**Comment by krystian3w** [comment]
ID #1876799 w CERT Polska/NASK.

**Comment by xMaap** [comment]
Najlepiej napisz do cert `cert@cert.pl https://cert.pl/posts/2020/03/ostrzezenia_phishing/ ` i pousuwa stronę nie tylko z KAD.
`https://www.virustotal.com/gui/url/5417eed4fc9f069e844503ca643a0aed17786184cc823fb4ac0047a394802ca5?nocache=1
`![Screenshot_20221025_223450](https://user-images.githubusercontent.com/36385327/197876491-a14abdb1-7328-4dbb-ac99-0809020f0309.png)
