### ISSUE TITLE
investtraderxreh.com

### ISSUE THREAD

**Issue by mino815** [FiltersHeroes/KAD#2240]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://ra2.investtraderxreh.com/
```

### Dodatkowe informacje mogące mieć znaczenie

Strona dzięki której będziemy "zarabiać" do 10000 euro miesięcznie :-)

**Comment by ClusterByte-x** [comment]
"RegisterPositionId": 78846,
        "DomainAddress": "ra2.investtraderxreh.com",
        "InsertDate": "2022-11-14T12:48:09",
        "DeleteDate": null

**Comment by krystian3w** [comment]
Przydałby się pewnie skrypt do wyłapania innych subdomen jak są w rekordach "DNS".

**Comment by krystian3w** [comment]
Skrypt zaczytał do pliku domenę, na tę chwilę w uBo/AdGuard zasięg rozszerzony do domeny (subdomena dla hosts/pi-hole bez regexów).

**Comment by krystian3w** [comment]
@hawkeye116477 bot się pomylił.
