### ISSUE TITLE
pierderediet.digital

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2249]
### Link bezpośredni 
`https://pierderediet.digital/MvCsrq`
### Dodatkowe informacje mogące mieć znaczenie
"BRODAWKI POWSTAJĄ W WYNIKU OBECNOŚCI PASOŻYTÓW W TWOIM ORGANIZMIE!
JEŚLI MASZ BRODAWKI NA SZYI, POD PACHAMI I W INNYCH MIEJSCACH – PASOŻYTY POŻERAJĄ CIĘ OD ŚRODKA!
Na dzień dzisiejszy istnieje tylko jedno rozwiązanie, które pozwala pozbyć się pasożytów. Jest to produkt przeciwpasożytniczy o nazwie Vormixil. Badania kliniczne przyniosły wspaniałe rezultaty. Eksport tego środka jest wstrzymany do momentu aż zostanie on rozdystrybuowany w całej Polsce."

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by ClusterByte-x** [comment]
Filtry KAD nie zajmują się już fake newsami czy blokowaniem stron rozpowszechniających pseudonaukę. 

O ile wskazany preparat, zapewne suplement diety jest dopuszczony do obrotu to nie budzi żadnych zastrzeżeń. 
Rzecz jasna, że w chorobach pasożytniczych lepiej stosować produkty lecznicze o udowodnionym i przebadanym działaniu leczniczym. Produkty ziołowe to ewentualnie wspomaganie właściwej farmakoterapii.

**Comment by ClusterByte-x** [comment]
Filtry KAD nie zajmują się już fake newsami czy blokowaniem stron rozpowszechniającymi pseudonaukę. 

O ile wskazany preparat, zapewne suplement diety jest dopuszczony do obrotu to nie budzi żadnych zastrzeżeń. 
Rzecz jasna, że w chorobach pasożytniczych lepiej stosować produkty lecznicze o udowodnionym i przebadanym działaniu leczniczym. Produkty ziołowe to ewentualnie wspomaganie właściwej farmakoterapii.

**Comment by ClusterByte-x** [comment]
Z polityki filtrów KAD-Przekręty zostały wykluczone strony rozpowszechniające pseudonaukę lub fake-newsy.

Strona, o ile reklamuje suplement diety dopuszczony do obrotu nie powinna budzić zastrzeżeń. 
Oczywistością jest, że w chorobach pasożytniczych właściwe stosowanie jest produktów leczniczych o udowodniony i przebadanym działaniu terapeutycznym, najlepiej skoordynowanym przez lekarza. Produkty ziołowe to jedynie wspomaganie właściwej farmakoterapii.

**Comment by krystian3w** [comment]
Sugerowane jest też używanie filtrów do blokowania reklam, wiele tego pochodzi właśnie z nich.
