### ISSUE TITLE
lista podejrzanych - pseudo firm pożyczkowych

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2251]
<div align="center">

### [Przejdź do pola komentarz "#issuecomment-new"](https://github.com/FiltersHeroes/KAD/issues/2251#issuecomment-new "Przejdź do pola komentarz '#issuecomment-new'")

(Link nie działa z dedykowaną aplikacją mobilną) (i o ile nie jesteś na czarnej liście organizacji zarządzającej repozytorium lub autora wątku)

</div>

<details><summary> dawny opis </summary>

### Dodatkowe informacje mogące mieć znaczenie

```markdown
https://www.czerwona-skarbonka.pl/lista-ostrzezen/
```

### Link bezpośredni do strony zawierającej oszustwo

linki z artykułu

</details>

**Comment by xMaap** [comment]
Działające strony i niezablokowany przez KAD.

```
certo-kancelaria.pl
kurcz-pozyczka.com
orange-finansow-polska.net
kviku.com
cashbro.net
creditron.org
wygodnepozyczki.pl
gotowkowe-pozyczki.pl
finantous.com
makura-usluga.com
kredytznajomego.pl
ofertanajuz.pl
ofertanajuz.pl
w1dzien-gotowka.pl
```
Pominąłem też `Archiwalna lista ostrzeżeń Czerwonej Skarbonki`.

**Comment by krystian3w** [comment]
Na pewno ten sam podmiot je dopisal na blogu?

**Comment by blocker999** [comment]
tak

**Comment by krystian3w** [comment]
Jak dla mnie wpis jest niewygodny, możesz wklejać nowe domeny codziennie najwyżej.
