### ISSUE TITLE
Strony malware

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2255]
```
oirc.zief.pl
www.qooircd.zief.pl
qoyproxim.ircgalaxy.pl
www.plilo.brenz.pl
www.5isohu.comaieov.comilo.brenz.pl
www.jll.chura.pl
www.ns3.trenz.pl
www.egmon.pl
````

### Dodatkowe informacje mogące mieć znaczenie

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
<html><body>


Nazwa domeny | zief.pl, ircgalaxy.pl, brenz.pl, chura.pl, trenz.pl, egmon.pl
-- | --
Stan | Aktywna w DNS [REGISTERED]
Utworzona | 2005.07.25 15:58:55
Ostatnia modyfikacja | 2013.01.17 18:39:17
Nazwy serwerów | sinkhole.cert.pl / sinkhole112.cert.pl [148.81.111.112] 
Abonent | NAUKOWA I AKADEMICKA SIEĆ KOMPUTEROWA  UL. KOLSKA 12 01-045 WARSZAWA, PL +48.223808300 Typ abonenta: organizacja Ostatnia modyfikacja: 2016.04.23 04:45:02
Rejestrator | NASK				ul. Kolska 12				01-045 Warszawa				Polska/Poland				+48.22 3808300				`info@dns.pl`


</body>
</html>
