### ISSUE TITLE
Błędne wpisy

### ISSUE THREAD

**Issue by LocalHeroPro** [FiltersHeroes/KAD#2267]
### Bloker (Blocker)

x

### Link bezpośredni, na którym występuje problem

Aktualizacja listy zwraca

```markdown
 [i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 85201 domains, 2 domains invalid!
      Sample of invalid domains:
      - eng-sub.xyz$all||wjnted.63sitestore.xyz
      - www.eng-sub.xyz$all||wjnted.63sitestore.xyz
  [i] List has been updated
```

### Opis błędu

Błędna wpisy

### Dodatkowe informacje mogące mieć znaczenie

Należy poprawić listę.

**Comment by krystian3w** [comment]
Poprawka wypchnięta: https://github.com/FiltersHeroes/KAD/actions/runs/3733034662

Za 10 minut powinna odświeżyć pamięć podręczną raw linków GitHub.
