### ISSUE TITLE
netflcpl.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2272]
### Link bezpośredni 
`https://netflcpl.com/`
### Dodatkowe informacje mogące mieć znaczenie
to jest scam

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Cert i Google zbanowało.

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/commit/31ba62e9e027c8722bb59033add0a19ae4ea53cf#diff-50722a3325584da687dc35a97b54ebb75db04e85da0e2531ab48492752fbec64R24516
https://github.com/FiltersHeroes/KAD/commit/4254487e4370b8515146405c9e61e5264dab7a44#diff-269381da98ff06dde11226ef06019e35651b7f1ddf78a517bb878a5dd5eaf038R39917
