### ISSUE TITLE
wtor.teconkilotr.site

### ISSUE THREAD

**Issue by mino815** [FiltersHeroes/KAD#2275]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://wtor.teconkilotr.site/
https://bav.globaltradruv.com/
https://basicsoeqx.space/?utm_campaign=3926
https://newss-eu.com/yrVpLk3k
https://fat.milproj.site/
https://epssn.polkilopola.xyz/
https://newrrweel.com/D5QgvjTk
```

### Dodatkowe informacje mogące mieć znaczenie

Gen-IX, whatsapp bot, Bitsoft, teslaX czyli programy umożliwiające "zarabianie" 30 tys miesięcznie z facebookowych sponsorowanych reklam

**Comment by xMaap** [comment]
Oprócz `newss-eu.com` wszystko jest dodane.
