### ISSUE TITLE
altra*.*

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2281]
### Link bezpośredni 
`https://www.altraspolska.com/`

### Dodatkowe informacje mogące mieć znaczenie

Strona to ewidentny scam. Żeby zamówić buty trzeba najpierw założyć konto i podać swoje dane, jak przechodzimy do płatności to jest tylko opcja do wpisania nr karty kredytowej. Brak regulaminu sprzedaży, adresu firmy itp. Wyświetlają się jako pierwsi w Google co dodaje wiarygodności. Scam działa od kilku lat tyle że zmieniał domeny:

```
https://www.altrapolska.com/
https://www.altrabuty.pl/
https://www.altrapolska.pl/
https://www.altrarunnerspolska.com/
https://www.altrarunningpl.com/
https://www.altraruningpolska.com/
```

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
W sumie duplikat: #1241

**Comment by krystian3w** [comment]
Duplicate of #1241
