### ISSUE TITLE
wyszukiwarkafilmow.pl (vod.plus)

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2286]
### Link bezpośredni 
`https://wyszukiwarkafilmow.pl/film?id=821&tytul=Szybcy%20i%20w%C5%9Bciekli%2010#`
### Dodatkowe informacje mogące mieć znaczenie
Fejkowa strona z filmami (np. film Szybcy i Wściekli 10, który będzie mieć premierę dopiero latem). Przekierowoje do rejestracji na innej stronie, gdzie po uiszczeniu opłaty dostępne są linki do legalnych serwisów.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
`vod.plus` jest już blokowane (uBo/AG/HOSTS/Pi-Hole), chętni mają około 30 dni na dopisanie innych przekierowań tutaj (tymczasowe konto Github) a potem jako nowe zgłoszenie (np. anonimowo).
