### ISSUE TITLE
objects-us-east-1.dream.io

### ISSUE THREAD

**Issue by roadriverrail** [FiltersHeroes/KAD#2289]
Your blocked domains list currently contains objects-us-east-1.dream.io, appearing in a file called "przekrety.txt", which translates as "scams" in English.  This domain is the S3-style object store for Dreamhost, a hosting service used by a very large customer base.  Because your block lists get used in a large number of ad blocking tools, any of my sites making use of Dreamhost Dreamobjects (which includes https://owncast.rhettaultman.com, https://mxks.dj, and https://splats.club) are being filtered by various ad blocking tools, including the pihole DNS system at my home.

I appreciate that you want to block scammers that make use of DreamObjects, but this negatively impacts legitimate devs like myself.  I doubt you'd block all of AWS or DigitalOcean in a similar way.  Is there some way my hosting service, which I've used since 1998, can please get off this block list?

**Comment by krystian3w** [comment]
Blacklisted by CERT Polska, <ins>**so few Poles even use this domain with default Polish ISP Provider**</ins>.

You can try report cure / FP by: https://incydent.cert.pl/domena#!/lang=en 

and at mail: cert@cert.pl

**Comment by krystian3w** [comment]
https://hole.cert.pl/domains/

```json
[
    {
        "RegisterPositionId": 91336,
        "DomainAddress": "objects-us-east-1.dream.io",
        "InsertDate": "2023-02-06T12:40:42",
        "DeleteDate": "2023-03-04T01:35:12"
    }
]

**Comment by roadriverrail** [comment]
@krystian3w Thank you for the noted deletion date.  I did contact CERT Polska and they confirmed with me they'd reinstated the domain.

I'm hearing from Dreamhost that this is a pervasive, global problem.  I'll continue working with them on it.
