### ISSUE TITLE
naturalsklep.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2292]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://naturalsklep.com/enga/acardin/20-nc/
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2023-03-13 17-50-43](https://user-images.githubusercontent.com/36385327/224771023-45567ef8-f114-4e5b-b669-ab82da676f03.png)
Plus fejkowe komentarze:
![Zrzut ekranu z 2023-03-13 17-51-01](https://user-images.githubusercontent.com/36385327/224771057-22ac171d-bd3d-4a87-b2a8-18ef0b3fdf9b.png)

**Comment by krystian3w** [comment]
#2190584
