### ISSUE TITLE
doladowania.pw

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2293]
### Link bezpośredni 
`https://doladowania.pw/` ->
`https://doladowania.tirk12.club/payment/73f7cc88ef1d`

### Dodatkowe informacje mogące mieć znaczenie
Fałszywa bramka doładowań
https://twitter.com/CERT_OPL/status/1637800536119320576

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Eset zbanował.
