### ISSUE TITLE
Dino 'nagrody'

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2296]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://sites.google.com/view/websiteoffciall2023a/halaman-muka
https://smrturl.co/o/267842/53210080?s1=GET
https://www.darmowy-konkurs.eu/79-k1deep/?session_id=102fb2473a02112bbd376fbe0f99d7&partner_id=1011&offer_id=46
```

### Dodatkowe informacje mogące mieć znaczenie

Z smrturl.co robi przekierowanie do darmowy-konkurs.eu.
darmowy-konkurs.eu są już blokowane przez KAD.
smrturl.co https://www.virustotal.com/gui/url/e82071271f7f30e364d091a87335aa159a73128c5e48c5b228ecb31d71e32820?nocache=1

**Comment by krystian3w** [comment]
`/click?pid=*&sub1=$document`

**Comment by krystian3w** [comment]
@kiboke cookie bars, can you address for ABP/Adblock, uBO & AdGuard?

```
https://www.szkolapl.org/home/ciekawostki/httpssites-google-comaszkolapl-orgwwwhome2ciekawostki
https://sites.google.com/a/szkolapl.org/www/home2/Ciekawostki
```
