### ISSUE TITLE
s3.us-east-005.backblazeb2.com

### ISSUE THREAD

**Issue by wiggum220** [FiltersHeroes/KAD#2304]
### Bloker (Blocker)

piHole

### Link bezpośredni, na którym występuje problem

```markdown
s3.us-east-005.backblazeb2.com
```

### Opis błędu

Blocking s3.us-east-005.backblazeb2.com blocks the entire S3 endpoint and all customers' buckets on that server. https://www.backblaze.com/b2/docs/s3_compatible_api.html

**Comment by krystian3w** [comment]
report bug too Polish Cert:

https://cert.pl/en/contact/

**Comment by wiggum220** [comment]
The issue was submitted to CERT.PL. They advised they have removed the domain from their warning list. Thank you!

**Comment by krystian3w** [comment]
Similar #2649
