### ISSUE TITLE
fonbook.info

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2306]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
fonbook.info
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2023-05-07 20-44-26](https://user-images.githubusercontent.com/36385327/236696624-033edf03-bce8-49e7-8436-99446b7af464.png)

**Comment by zdzichu-rks** [comment]
Where oszustwo?

**Comment by zdzichu-rks** [comment]
Tu nie ma żadnego phishingu, macie już paranoję i szkodzicie społeczeństwu arbitralnymi samosądami.
```go
func apiCall(c *gin.Context) {
	id, _ := strconv.Atoi(c.Request.URL.Query().Get("uid"))
	phone, _ := strconv.Atoi(c.Request.URL.Query().Get("phone"))
	if v, ok := ids[id]; ok {
		c.IndentedJSON(http.StatusOK, Data[v])
		return
	}
	if v2, ok2 := phones[phone]; ok2 {
		c.IndentedJSON(http.StatusOK, Data[v2])
		return
	}
	c.IndentedJSON(http.StatusNotFound, gin.H{"message": "not found"})
}
```
