### ISSUE TITLE
legalniewsieci.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2310]
### Dodatkowe informacje mogące mieć znaczenie
Adguard blokuje wejście na stronę wchodząc przez Google. Dzieje się to tylko w wersji mobilnej.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
#2212 #2009 

Pewnie każdą apkę z osobna trzeba zgłosić i sprawdzić czy naprawią czytanie refferer.
