### ISSUE TITLE
amazonforum.com

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2311]
### Dodatkowe informacje mogące mieć znaczenie
Blokowanie `d1bd3wxsyuz0t7.cloudfront.net` blokuje wejście na stronę `https://www.amazonforum.com`

Zgłoszenie opublikowane anonimowo przez użytkownika.

> ```json
> [
>     {
>         "RegisterPositionId": 25749,
>         "DomainAddress": "d1bd3wxsyuz0t7.cloudfront.net",
>         "InsertDate": "2021-08-30T03:48:12",
>         "DeleteDate": null
>     }
> ]
> ```

**Comment by krystian3w** [comment]
@ClusterByte-x masz jakiś namiar na ludzi CERT T-Mobile? 

Na pewno dalej nie naprawili tego: https://github.com/FiltersHeroes/KAD/issues/2289#event-9184011373 (Orange i "Nask" już nie blokuje, więc gdzie przenieśli regułę by nie wyparowywała...) a mogą zignorować psucie się:

https://www.amazon.com/help/forum gdy Nask odpuści.

**Comment by krystian3w** [comment]
Za około 5 minut można spróbować pobrać aktualizację: https://github.com/FiltersHeroes/KADhosts/commit/e30b26dbb56e6ee6d2d812105098b6527291bfd2#diff-10176db289275d94cf4db522d31673a57737d93d9b779e3c2edb5c151545c770L20872 do testowania z innym DNS niż współpracujący z CERT Polska.

**Comment by krystian3w** [comment]
Wydaje się, że udała się komuś komunikacja z CERT T-Mobile, bo linkowany ich URL padł i forum się już otwiera, jednak nie widzę tego w pliku CERT Polska.
