### ISSUE TITLE
ipfs public gateways

### ISSUE THREAD

**Issue by KonoromiHimaries** [FiltersHeroes/KAD#2314]
### Bloker (Blocker)

ubo 1.49.2

### Link bezpośredni, na którym występuje problem

https://ipfs.github.io/public-gateway-checker
https://ipfs-public-gateway-checker.on.fleek.co

### Opis błędu

Do (za/od)blokowania.

``` yml
uBo logger:
 dweb.link
 aragon.network
 crustwebsites.net
 parkingcrew.net
 best-practise.se
 pinata.cloud
```

**Comment by krystian3w** [comment]
Tylko: jak nie da się wkleić ze 60 tysięcy domen to filtrowanie zajmie z 42 dni powiewając 1 minutę na domenę.

I trzeba by co ban z CERT sprawdzać czy to oni blokują Gate.

**Comment by krystian3w** [comment]
Zainteresowani mają około 40 dni na podsumowanie jak problem inaczej zaadresować.

**Comment by KonoromiHimaries** [comment]
@krystian3w Nie można po prostu whitelistować popularnych domen ipns na wszystkich bramkach, a resztę zablokować?

**Comment by krystian3w** [comment]
Wiele dodanych do skip już ma błąd 410 lub błąd połączenia.

**Comment by krystian3w** [comment]
Nie widzę nigdzie nic z `ipfs.tech`:

![obraz](https://github.com/FiltersHeroes/KAD/assets/35370833/ccaf6cfe-cab0-4688-ad6e-a8261468e5e1)

Jak bardzo chcesz to subdomeny możesz wypisać lub zrobić PR i CERT ich u nas nie zbanuje.

**Comment by KonoromiHimaries** [comment]
Nie chodziło mi o blokowanie `ipfs.tech` przez cert.

**Comment by KonoromiHimaries** [comment]
`ipfs.tech` jest w porządku, nie udostępnia żadnej bramki. Zobacz
```
https://ipfs.tech/ipfs/bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq
```

Więc nie ma sensu go blokować lub odblokowywać. To jest oficjalna strona ipfs.

**Comment by krystian3w** [comment]
To raczej problem "obszedłnięty" aż CERT nie uprości tych banów hasha na blokadę subdomeny i domeny:

https://github.com/FiltersHeroes/KAD/blob/03241362603b826ec2c9365e4d62a7c01c34af3c/sections/przekrety.txt#L9607-L9661

Do filtru typu:

https://github.com/FiltersHeroes/KAD/blob/03241362603b826ec2c9365e4d62a7c01c34af3c/sections/przekrety.txt#L33816-L33817

I tamte zostaną dodane do nowych jako 84+.

**Comment by KonoromiHimaries** [comment]
@krystian3w lista cid/hash do blokowania `https://badbits.dwebops.pub/denylist.json`

**Comment by KonoromiHimaries** [comment]
Tak jak w filtrach od ubo, raz na 5 dni wystarczy.

**Comment by krystian3w** [comment]
Trochę boję się, że wtedy to powinno iść do osobnego pliku z obowiązkowym wykluczeniem iOS*, by w mobilnym Safari nie padało blokowanie reklam, trackerów i śledzenia.

Bo oba pliki mają po 155442 linii (aplikacja może to przemnożyć jak uBo przez 5+ i mamy nagle 777K a iOS pewnie dalej ma maksymalnie z 330K).

\* - Jak to ma być blokowanie 155K "hashy" z pomijaniem domeny czyli np.

```adb
||gffgfdgggr6745fdftedf46636defggeetr66eery5644yt.*$all,important
```


Opcjonalnie musisz napisać instrukcję obsługi tych plików, bo się na tym nie znam i nie wiem ile lat wymaga wdrożenie by je zrozumieć.

**Comment by KonoromiHimaries** [comment]
Tak, można wykluczyć safari z blokowania lub zablokować same bramki oprócz tych, co mają zainstalowany to rozszerzenie.
