### ISSUE TITLE
instedi.site

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2319]
### Link bezpośredni 
`https://instedi.site/`
### Dodatkowe informacje mogące mieć znaczenie
Podszywanie po rząd, scam/phishing

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Cert zbanował: https://cert.t-mobile.pl/alert.php?url=c5dd23a3c5df7fd2d665eae2e77ec57e

**Comment by tommyklab** [comment]
Tak, wysłałem im też :)
Stronka jeszcze działa  (po 9 godzinach, na VT 5 AV wykrywa)
Tego scamu z UA coraz więcej ;(
