### ISSUE TITLE
Wyłudzanie informacji finansowej

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2320]
### Link bezpośredni 
`https://gminny-orodek-kultury-w-raczka.sitey.me`
### Dodatkowe informacje mogące mieć znaczenie
Wyłudzanie informacji finansowych poprzez podszywanie się pod instytucje na Facebook.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Mnie przestało działać.
