### ISSUE TITLE
`0lx.57683329.xyz` | `inpoost.8485151.xyz`

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2335]
### Link bezpośredni 
`https://4lvy.me/`
### Dodatkowe informacje mogące mieć znaczenie
Od razu po wystawieniu ogłoszenia, pojawiły się linki w stylu:
```
https://4lvy.me/tzwywh
https://4lvy.me/Zgmrna
```
Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Nie blokujemy usług skracania linków.
