### ISSUE TITLE
AdGuard znowu blokuje strony, wchodząc przez Google

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2336]
### Dodatkowe informacje mogące mieć znaczenie
Wejście przez Google na:
```
chomikuj.pl
legalniewsieci.pl
allegrolokalnie.pl
```

Jest blokowane przez Aduard wersja 4.2.151 przeglądarka Chrome wersja 116.0.5845.179

<details>

![](https://i.imgur.com/ixQRo9O.png)
![](https://i.imgur.com/rLZUOqq.png)
![](https://i.imgur.com/fsUNpwF.png)

</details>

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Błąd rozszerzenia, nie powinno tak robić.

Możliwe, że trzeba będzie na stałe zrobić dopuszczenie do urwanych w wildcardach i regexach dopuszczenie referrer.
