### ISSUE TITLE
praca-oix.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2337]
### Link bezpośredni 
`http://praca-oix.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Logowanie via FB

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Cert mógłby zablokować (#2538409)

**Comment by krystian3w** [comment]
Wygląda, że dostali bana od https://hawkhost.com
