### ISSUE TITLE
twoje-potwierdzenie.com

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2339]
### Dodatkowe informacje mogące mieć znaczenie

podobna sprawka co ta w artykule: https://www.dobreprogramy.pl/wyludzacze-danych-kusza-kartami-podarunkowymi-do-biedronki,6628543211518081a
więc twierdze że to prawdopodobnie wyłudzenie danych przez  firme toleadoo GmbH .

![fałszywy konkurs](https://github.com/FiltersHeroes/KAD/assets/23176832/e59fe17f-21fb-4f79-b754-e279005908f6)

**Comment by krystian3w** [comment]
Problem jak grzyby po deszczu, możliwe że musisz zorganizować "honeypot" i AI do odsiewania legalnych formularzy.
