### ISSUE TITLE
`my.demio.com`

### ISSUE THREAD

**Issue by Sol1du2** [FiltersHeroes/KAD#2341]
Hey guys.

I wanted to ask the reasoning behind blocking the domain `my.demio.com`? I noticed it being blocked on my pihole and traced it back to your list. My girlfriend uses it for work. It's a marketing platform for hosting webinares to potential clients. Basically a live streaming service. Wondering if it was something else when it was added or if there is a good reason to block their service. Their main page, `www.demio.com` is not blocked.

Thanks.

**Comment by krystian3w** [comment]
These looks as scam/fraud: `https://my.demio.com/ref/sdzQ7d6D7ltwGTD7`

**Comment by krystian3w** [comment]
So far, no one reported that there would be more of this; so the site can be unblocked at the HOSTS/DNS level, so it will be blocked already only for uBlock Origin and AdGuard users.


In part, the scam has lost its polonization, so only a polonized Facebook post could be a reason for blocking in regional "KAD Anti-Scams 🇵🇱".
