### ISSUE TITLE
gizycko.info.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2348]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://gizycko.info.pl/cgi-sys/suspendedpage.cgi
```

### Dodatkowe informacje mogące mieć znaczenie

![giż](https://github.com/FiltersHeroes/KAD/assets/23176832/42473df1-ebb9-4ddc-9b67-92eb6765e8e1)

**Comment by krystian3w** [comment]
Admin serwera ich zdjął, raczej będą mieć trudny powrót bez postawienia strony WWW od zera.
