### ISSUE TITLE
hurt.com.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2354]
### Bloker (Blocker)

uBlock Origin 1.52.0

### Link bezpośredni, na którym występuje problem

```markdown
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/document-blocked.html?details=%7B%22url%22%3A%22https%3A%2F%2Fwww.hurt.com.pl%2Frouter-mi-fi-wi-fi-z-4g-lte-alcatel-link-zone-mw40v-p15984.html%22%2C%22hn%22%3A%22www.hurt.com.pl%22%2C%22dn%22%3A%22hurt.com.pl%22%2C%22fs%22%3A%22%7C%7Churt.com.pl%5E%24document%22%7D
```

### Opis błędu

blokada strony niby czemu ?

### Dodatkowe informacje mogące mieć znaczenie

![hurt](https://github.com/FiltersHeroes/KAD/assets/23176832/6837fd6a-48c9-42e7-a2f3-d6ce466448dc)

**Comment by hawkeye116477** [comment]
Chyba najwyraźniej ktoś zgłaszał tutaj => https://github.com/FiltersHeroes/KAD/issues/1241 i @krystian3w dodał (https://github.com/FiltersHeroes/KAD/commit/008100b2a).
