### ISSUE TITLE
AdGuard nie blokuje stron?

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2355]
### Dodatkowe informacje mogące mieć znaczenie
AdGuard nie blokuje stron na które wchodzi się bezpośrednio przez pasek adresu.
Dziennik AdGuard pokazuje "jakieś" blokowanie stron niżej dwa przykłady.

plushdogry.pl | Dziennik filtrowania
--- | ---
![](https://i.imgur.com/IJ6e85Y.png) | ![](https://i.imgur.com/t9JCdg8.png)

pol-dywan.pl | Dziennik filtrowania
--- | ---
![](https://i.imgur.com/Zb2BBVK.png) | ![](https://i.imgur.com/GJrcXHh.png)

W Chrome Jak się zaznaczy adres strony i kliknie "Przejdź do strony" to blokuje wejście (otwarcie karty ze stroną).
I tak samo jest w Firefox jak po kliknięciu "Odtwórz odnośnik w nowej karcie".

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
W uBo jest OK:

https://github.com/FiltersHeroes/KAD/blob/58c5ed11bbbc266ea9dbd10748d6ac3b036ad6ad/sections/przekierowujace_do_przekretow.txt#L180
https://github.com/FiltersHeroes/KAD/blob/58c5ed11bbbc266ea9dbd10748d6ac3b036ad6ad/sections/podejrzane_inne_oszustwa.txt#L1449

@adamwr możesz pchnąć oba tematy w CoreLibs?

Jak trzeba to można nam przyznać w FiltersRegistry uprawnienia do m.in. skryptletów/CSS, jak tego wymaga nowszy parser do działania `all` z planszą ostrzegawczą.

https://github.com/FiltersHeroes/KAD/blob/master/sections/natretne_lub_wprowadzajace_w_blad.txt#L26-L30

https://github.com/FiltersHeroes/KAD/blob/master/sections/natretne_lub_wprowadzajace_w_blad.txt#L1

**Comment by krystian3w** [comment]
Zgłaszający może przetestować takie coś, ale raczej nie będziemy przebudowywać przez to kompilatora:

```abp
||plushdogry.pl^$document,important
||pol-dywan.pl^$document,important
```

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2579
