### ISSUE TITLE
carpatree.com

### ISSUE THREAD

**Issue by szwagier44** [FiltersHeroes/KAD#2361]
### Bloker (Blocker)

Pi-hole v5.17.2

### Link bezpośredni, na którym występuje problem

```markdown
https://carpatree.com/pl
```

### Opis błędu

Domena carpatree.com jest blokowana, a zawiera stronę prawdziwego sklepu z ubraniami. Żona mi głowę przez to suszy :) 

### Dodatkowe informacje mogące mieć znaczenie

![2023-11-19_20h40_19](https://github.com/FiltersHeroes/KAD/assets/28534045/113e84fc-61a8-4ba1-890a-7b122b2fed4d)

**Comment by krystian3w** [comment]
Pi Hole powinno widzieć poprawkę jeszcze dzisiaj jak nie korzystasz z np. https://github.com/StevenBlack/hosts

https://github.com/FiltersHeroes/KADhosts/commit/ef8c8ea905ae1fe9fe9daedfb03c452bf89717d1
https://github.com/FiltersHeroes/KADhosts/commit/a2ff8fa420bda46f87cb0a9ff0d031fffec78d9c
