### ISSUE TITLE
one-bookingline.com

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2369]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
one-bookingline.com
```

### Dodatkowe informacje mogące mieć znaczenie

https://www.egospodarka.pl/184974,Oszustwo-na-Booking-Cyberprzestepcy-wabia-atrakcyjna-praca,1,12,1.html

**Comment by krystian3w** [comment]
Ja nie widzę polskiego w formularzu, więc ban w gestii CERT lub hawkeye.

**Comment by krystian3w** [comment]
CERT uznał słuszność bana około 14:41:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<Rejestr>
<PozycjaRejestru Lp="163021">
    <AdresDomeny>one-bookingline.com</AdresDomeny>
    <DataWpisu>2023-12-20T14:41:11</DataWpisu>
</PozycjaRejestru>
</Rejestr>
```
