### ISSUE TITLE
czyjtonumer.net

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2374]
### Bloker (Blocker)

uBlock Origin 1.54.0

### Opis błędu

Blokada strony, niewiem czy słuszna ?.

### Dodatkowe informacje mogące mieć znaczenie

https://www.dobreprogramy.pl/czyj-to-numer-oto-jak-latwo-sprawdzisz-kto-dzwonil,6973698182433440a : tu autor newsa wymienia tą stronę jako przydatną.

**Comment by krystian3w** [comment]
Nieprzydatna, jak nie mają nic o numerze to żądają 30 zł by w ramach "newslettera" otrzymać po latach informację, że nie odebrałeś telefonu od telemarketerki np. fotowoltaiki niekompatybilnej z blokowiskami w miastach.

```adb
,from=~uwazaj-na-pakiet-premium.*
```

From użyłem jako komentarza.
