### ISSUE TITLE
xxx-stores.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2375]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
it-bluestone.xxx-stores.com
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2023-12-28 10-04-11](https://github.com/FiltersHeroes/KAD/assets/36385327/6e2a035d-b999-44e2-a2b8-5dce394e6ccd)

**Comment by krystian3w** [comment]
#2331
