### ISSUE TITLE
dobreprogramy.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2379]
### Link bezpośredni 
`https://www.dobreprogramy.pl/scribus,program,windows,6628724744758913`
### Dodatkowe informacje mogące mieć znaczenie
Ukrywa opis i screeny.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Na uBo z dobrym wsparciem `:has()` problemu nie widzę, więc zostaje:
- AdGuard, 
- uBo na przeglądarce Firefox gdzie `:has()` działa jakby nie chciało (starsze od 121 lub 123)
- uBo legacy
- ułomna translacja z privoxy (niespierane)

**Comment by krystian3w** [comment]
@adamwr masz pomysł jak to przerobić na kompatybilny filtr dla AdGuard:

```adb
www.dobreprogramy.pl#?#article#main-content > div[class]:not([id]) > div[class]:not([id]):has(> div[class]:not([id]) > div:not([class]):not([id]) > div[class]:not([id]) > a[class][href*="niepotrzebne-pliki"][href*=","]:not([id]):has-text(naszego poradnika)) > div:nth-child(-n+2):not(:empty):not(:has(a[href*="oprogramowanie-z-rosji"], a[href*="niepotrzebne-pliki"])):matches-path(/\/[a-zA-Z0-9-]{1,99},program,/)
```

https://github.com/FiltersHeroes/KAD/blob/4290d3e49dde0bc07b6880f64b26b6bbdb9b81aa/sections/natretne_lub_wprowadzajace_w_blad.txt#L24

Tak by nie czekać na dodatek 4.4 lub aplikację z nowymi "ExtendedCSS".

**Comment by AdamWr** [comment]
Jeśli się nie mylę, to problem jest ogólnie z `:not()`.
Usunięcie wszystkich `:not()` wydaje się działać prawidłowo:
```adblock
[$path=/\\/\[a-zA-Z0-9-\]{1\,99}\,program\,/]www.dobreprogramy.pl#?#article#main-content > div[class] > div[class]:has(> div[class] > div > div[class] > a[class][href*="niepotrzebne-pliki"][href*=","]:has-text(naszego poradnika)) > div:nth-child(-n+2):has([class]:contains(/[Aa]systenta|poradnika/))
```
