### ISSUE TITLE
skinheaven.pl

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2380]
### Link bezpośredni 
`https://skinheaven.pl/`
### Dodatkowe informacje mogące mieć znaczenie
Szanowni Państwo,

W imieniu firmy SkinHeaven, która specjalizuje się w sprzedaży urządzeń kosmetycznych i działa pod adresem https://skinheaven.pl/, pragniemy wyrazić nasze zdumienie i niepokój związane z zaklasyfikowaniem naszej strony internetowej przez Państwa system filtrujący. Nasza firma od lat cieszy się nienaganną reputacją i zaufaniem tysięcy klientów, zawsze działając w sposób w pełni legalny i transparentny. Chcemy podkreślić, że nigdy nie byliśmy związani z żadnymi nieuczciwymi praktykami, co dodatkowo wzmacnia nasze zdziwienie w związku z tą sytuacją. Ponadto, nasza strona nie figuruje na listach ostrzeżeń takich jak CERT Polska, legalniewsieci.pl czy Komisji Nadzoru Finansowego.

W związku z powyższym, uprzejmie prosimy o udzielenie informacji na temat podstaw, na jakich nasza strona została umieszczona na Państwa liście blokowanych stron. Czy istnieje możliwość, że doszło do pomyłki lub nieporozumienia po Państwa stronie? Jesteśmy otwarci na dialog i gotowi dostarczyć wszelkie potrzebne informacje w celu wyjaśnienia tej
sytuacji.

Chciałbym również zaznaczyć, że w przypadku braku odpowiedzi lub wyjaśnień z Państwa strony, będziemy zmuszeni rozważyć podjęcie odpowiednich kroków prawnych. Taka sytuacja może bowiem niesłusznie szkodzić reputacji naszej firmy, powodować straty finansowe oraz zakłócać naszą działalność gospodarczą. Mamy nadzieję, że nie będzie to konieczne i że sprawa zostanie rozwiązana w sposób satysfakcjonujący dla obu stron.

Z wyrazami szacunku,
Adrian Rozmus
https://skinheaven.pl

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by xMaap** [comment]
https://web.archive.org/web/20230425202418/https://skinheaven.pl/regulamin/

Z Chin już przestaliście wysyłać?

**Comment by krystian3w** [comment]
Nie wiem czy załozą konto na GitHub, najpewniej liczą na opis w postaci mejla (szkoda pieniędzy na wysłanie listu Pocztą Polską za potwierdzeniem odbioru).

**Comment by xMaap** [comment]
Jak coś to pozwij jeszcze ich https://www.virustotal.com/gui/url/bef86bb645e44fe6f2152fafabe4e189606bc9eae8a3abab87fd833454d803f4?nocache=1
![Zrzut ekranu z 2024-01-05 15-38-57](https://github.com/FiltersHeroes/KAD/assets/36385327/9916de49-f9eb-4d5c-8285-e705f33da7ea)

**Comment by SkinHeaven** [comment]
Szanowni Państwo,

W odpowiedzi na Państwa zapytania i wątpliwości dotyczące naszej działalności i przyczyn zakwalifikowania strony https://skinheaven.pl/ do filtra KAD, pragniemy przedstawić kilka kluczowych faktów.

Przede wszystkim, pragnę podkreślić, że nasza firma nigdy nie prowadziła wysyłki towarów z terytorium Chin. Choć przez pewien czas działaliśmy jako pośrednik, wszelkie oferowane przez nas urządzenia zawsze były wysyłane bezpośrednio z terytorium Polski, zapewniając 1-2 dniowy czas dostawy. Nawet w naszym archiwalnym regulaminie znajduje się zapis potwierdzający tę praktykę.

Jesteśmy firmą, która zajmuje się dystrybucją obradowanych urządzeń, działając zawsze zgodnie z obowiązującymi przepisami. Sugerowanie, że nasza działalność może być związana z nieuczciwymi praktykami na podstawie interpretacji regulaminu lub opinii kilku osób, jest nie tylko błędne, ale i krzywdzące. Nasza firma cieszy się zaufaniem i pozytywnymi opiniami tysięcy klientów, co jest najlepszym dowodem na naszą rzetelność i transparentność działania.

Dodanie naszej strony do filtra stron podejrzanych o oszustwa bez rzetelnej weryfikacji faktów jest działaniem nie tylko niesprawiedliwym, ale i potencjalnie szkodliwym dla naszej reputacji oraz interesów biznesowych. Mamy nadzieję, że osoba odpowiedzialna za tę decyzję zdaje sobie sprawę z potencjalnych konsekwencji prawnych wynikających z takiego działania.

Podkreślamy, że SkinHeaven to nie mała firma - obsługujemy tysiące klientów rocznie. Działania, takie jak bezpodstawne dodanie naszej strony do filtra KAD, bez wnikliwej weryfikacji i dialogu z nami, szkodzą naszej działalności i wizerunkowi. W związku z tym, poważnie rozważamy podjęcie odpowiednich kroków prawnych, mając na uwadze pochopność i brak rzetelnej weryfikacji w podjęciu decyzji o zakwalifikowaniu naszej strony do filtra KAD.

Z wyrazami szacunku,
Adrian Rozmus

**Comment by xMaap** [comment]
`Nasza firma cieszy się zaufaniem i pozytywnymi opiniami tysięcy klientów, co jest najlepszym dowodem na naszą rzetelność i transparentność działania.`

Gdzie macie tysiące opinii?

https://www.alibaba.com/product-detail/High-Intensity-Focused-Ultrasound-Mini-Hifu_1600984780317.html?s=p
https://pl.aliexpress.com/item/1005003173117681.html

**Comment by SkinHeaven** [comment]
> `Nasza firma cieszy się zaufaniem i pozytywnymi opiniami tysięcy klientów, co jest najlepszym dowodem na naszą rzetelność i transparentność działania.`
> 
> Gdzie macie tysiące opinii?
> 
> https://skinheaven.pl/produkt/urzadzenie-anti-aging-dermalift-pro/ https://www.alibaba.com/product-detail/High-Intensity-Focused-Ultrasound-Mini-Hifu_1600984780317.html?s=p

Głównym kanałem naszych działań reklamowych są media społecznościowe i to właśnie tam, pod naszymi reklamami, znajduje się zdecydowana większość opinii naszych klientów.

Co do przesłanego linku, nie rozumiem jaki ma on związek z obecną sytuacją?

W tym momencie nie zamierzam angażować się w dyskusje na tematy niezwiązane z główną kwestią. Oczekuję oficjalnych informacji i wyjaśnień dotyczących przyczyn zaklasyfikowania naszej strony internetowej do filtra KAD.

**Comment by krystian3w** [comment]
W lutym tego roku został uznany za fejkowy (np. tylko do Pishingu kart kredytowych).

Jak widać nawet podwójna/potrojna ludzka weryfikacja zawodzi.
