### ISSUE TITLE
allegrolokalnie.

### ISSUE THREAD

**Issue by nightznero** [FiltersHeroes/KAD#2383]
### Bloker (Blocker)

ADG

### Link bezpośredni, na którym występuje problem

```markdown
https://t.allegrolokalnie.pl/wiadomosci/XYZ
```

### Opis błędu

allegrolokalnie jest ~~w zasadzie ale wydaje mi się że jeszcze potrzeba dodać `~*.allegrolokalnie.pl`, bo syntax chyba ma jakiś problem i blokuje~~

### Dodatkowe informacje mogące mieć znaczenie

![Screenshot_20240108_182209](https://github.com/FiltersHeroes/KAD/assets/61750641/97522234-adb7-4168-962b-fc8ba3329bfa)
![Screenshot_20240108_182226_Brave](https://github.com/FiltersHeroes/KAD/assets/61750641/fa5cb033-28cd-464a-8820-f50e12887ab5)

**Comment by krystian3w** [comment]
To błąd logiki silnika AdGuard musisz opisać im to swoimi słowami to może naprawią za 8-12 miesięcy.
