### ISSUE TITLE
columnistasia.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#2395]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://columnistasia.com/bose-portable-smart-speaker-review-75589
https://gadgetgemhub.xyz/c/WDKaNYSwx8xXssT8pHapEoxn38O?s1=10246c162f35df3929adc0376b4533&s2=1157&s3=&offer_id=18594&s4=&p_id=
```

### Dodatkowe informacje mogące mieć znaczenie

![Zrzut ekranu z 2024-02-15 15-07-32](https://github.com/FiltersHeroes/KAD/assets/36385327/1929023f-1767-4573-bf8d-9f477315daf6)
![Zrzut ekranu z 2024-02-15 15-08-38](https://github.com/FiltersHeroes/KAD/assets/36385327/1ebacefd-9394-474c-aed3-18d3c7e75687)

**Comment by hawkeye116477** [comment]
```
https://www.hybrid-analysis.com/sample/a664cea91cc0a88f9d06d7d2eccdf154044f96a88c63b04650f3091db2d7e842/65dc7800a385c4c0ea09339a
https://www.hybrid-analysis.com/sample/bf5e01de3794fd26acba45877b9663b09234b2e4f5f93a5a642a42a2030b8423
```
