### ISSUE TITLE
camelie.pl

### ISSUE THREAD

**Issue by szwagier44** [FiltersHeroes/KAD#2398]
### Bloker (Blocker)

Pi-hole v5.17.3

### Link bezpośredni, na którym występuje problem

```markdown
camelie.pl
```

### Opis błędu

false positive - pod tym adresem znajduje się działający sklep z bielizną.

### Dodatkowe informacje mogące mieć znaczenie

![image](https://github.com/FiltersHeroes/KAD/assets/28534045/c17c5b00-619c-423a-a01c-b5a4fcebdc10)

**Comment by hawkeye116477** [comment]
https://github.com/FiltersHeroes/KAD/issues/1241

**Comment by szwagier44** [comment]
wycofuje zgłoszenie błędu. Czytając opinie o sklepie chyba muszę zweryfikować.
