### ISSUE TITLE
CERT v2.0

### ISSUE THREAD

**Issue by nightznero** [FiltersHeroes/KAD#2407]
Witajcie, jakiś czas temu _CERT_ wydał nową wersję list.

   Aktualnie jest wersja v2,
      gdzie domeny są aktywne przez 6 msc. 
         Zauważyłem że na waszej stronie jest odnośnik do starych list więc albo dalej jest używane stare źródło lub zapomnieliście zmienić odnośnika.

Link z waszej strony -> `https://cert.pl/posts/2020/03/ostrzezenia_phishing/`

Link do wersji v2 -> `https://cert.pl/lista-ostrzezen/`

a tutaj już odnośniki do samych list:

* **Domains**: `https://hole.cert.pl/domains/v2/domains.txt`

* **ADB**:`https://hole.cert.pl/domains/v2/domains_adblock.txt`

* **HOSTS**:`https://hole.cert.pl/domains/v2/domains_hosts.txt`

Pozdrawiam, NIGHTZNERO.

**Comment by krystian3w** [comment]
Pytanie czy przekręt nie wróci po 6 miesiącach do żywych a oni wykreślą i tylko T-Mobile nie cofnie bana.

**Comment by krystian3w** [comment]
Dodatkowo nie widzę na KADAntiScam.netlify.app tego linka z 2020.

**Comment by krystian3w** [comment]
Wychodzi że T-Mobile dalej używa V1.

**Comment by krystian3w** [comment]
Można im spróbować wyjaśnić czym się to rożni i czy są zainteresowani udostępniać mniejszą wersję listy.

**Comment by FadeMind** [comment]
@krystian3w jakie są zasadnicze różnice by im to krótko streścić? :> Sam chciałem im po prostu napisać o nowej wersji, ale pomyślałem, że to Wy się znacie (jako team) na sprawie, więc napisałem tutaj.

**Comment by krystian3w** [comment]
W skrócie przez 182-183 dni obserwują czy domena została oczyszczona z oszustwa np. z winy przestarzałego oprogramowania witryny (lub zdjęta przez administratorów hostingu) - jak zaszło jedno z dwóch to znika z listy do kolejnego zgłoszenia, że znów została zainfekowana.

**Comment by nightznero** [comment]
> @krystian3w jakie są zasadnicze różnice by im to krótko streścić? :> Sam chciałem im po prostu napisać o nowej wersji, ale pomyślałem, że to Wy się znacie (jako team) na sprawie, więc napisałem tutaj.

Już zrobiłem request `https://github.com/AdguardTeam/HostlistsRegistry/issues/488#issue-2264230717`
