### ISSUE TITLE
fałszywye domeny bankowości elektronicznej.

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2420]
https://pl.linkedin.com/posts/csirt-knf_strony-internetowe-tworzone-przez-cyberprzest%C4%99pc%C3%B3w-activity-7208416704119377920-sfyx

![image](https://github.com/FiltersHeroes/KAD/assets/23176832/3b928fe5-8043-4e62-8378-0d4f7bcb259a)

**Comment by krystian3w** [comment]
Lipa że obrazek - trzeba OCR lub przepisywać.

**Comment by krystian3w** [comment]
2 z 5 są offline (błąd połączenia lub jakiś placeholder hostingu) a resztę zablokował CERT jako phishing.
