### ISSUE TITLE
`*altra*.*`

### ISSUE THREAD

**Issue by PolishRoboDog** [FiltersHeroes/KAD#2427]
### Link bezpośredni 
`https://www.altra-pl.com/`
### Dodatkowe informacje mogące mieć znaczenie
Inne adresy:

```adb
https://www.altrapolska.org/
https://www.sklepaltrapolska.com/
https://www.altraruning-polska.com/
https://www.altrarunningpoland.com/
```

Fałszywe witryny wyłudzające dane/nr kart kredytowych, imitują oficjalną stronę, przyciągają atrakcyjnymi cenami butów znanej marki. Są dosyć wysoko w rankingach Google co dodaje im wiarygodności. Brak informacji o podmiocie odpowiedzialnym, płatność wyłącznie za pomocą karty kredytowej.  Co jakiś czas są tworzone nowe strony z lekko zmienioną nazwą domeny, scam działa co najmniej od dwóch lat.

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
Duplicate of https://github.com/FiltersHeroes/KAD/issues/1241

**Comment by krystian3w** [comment]
Duplicate of https://github.com/FiltersHeroes/KAD/issues/2281
