### ISSUE TITLE
www.hotpxuq.shop - fake sklep

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#2462]
### Link bezpośredni do strony zawierającej oszustwo

```markdown
https://www.hotpxuq.shop/
```

### Dodatkowe informacje mogące mieć znaczenie

fake sklep

**Comment by krystian3w** [comment]
CERT zbanował, szansa że cofną raczej niska.

**Comment by krystian3w** [comment]
Duplicate of #1241
