### ISSUE TITLE
revolut-account-poland.com

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2526]
Link bezpośredni do strony zawierającej oszustwo:

`revolut-account-poland[.]com//vqxngksh`

### Dodatkowe informacje mogące mieć znaczenie

https://www.gsmmaniak.pl/1538259/podejrzane-smsy-revolut-oszustwo/

**Comment by krystian3w** [comment]
`account-poland.com` offline, wildcard lub regex może uwalić coś.

**Comment by krystian3w** [comment]
`revolut-account-poland.com` jest online, jedynie Google i Microsoft zbanowały domenę (np. Windows Defender na PC/notebooku), CERT Polska jakby utonął w zgłoszeniach (gdy chociaż CERT Orange wysłał zgłoszenie do CERT Polska).

**Comment by krystian3w** [comment]
https://github.com/FiltersHeroes/KAD/blob/0e51726c880abd3084067d1c8e802a151122bb40/sections/przekrety.txt#L36181
