### ISSUE TITLE
vidaxl.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/KAD#2533]
### Bloker (Blocker)

uBlock Origin 1.61.2

### Link bezpośredni, na którym występuje problem

```markdown
https://www.vidaxl.pl/g/596/ozdoby-sezonowe-i-swiateczne
```

### Opis błędu

czemu blokada ?

### Dodatkowe informacje mogące mieć znaczenie

![vida](https://github.com/user-attachments/assets/e0659848-fced-4e03-8340-1881a578c22b)

**Comment by krystian3w** [comment]
Portal ma niskie opinie, więc nie warto się sugerować reklamami w telewizji.

https://www.ceneo.pl/sklepy/vidaxl.pl-s25262

![obraz](https://github.com/user-attachments/assets/3c9f75f7-a2a9-4c3d-a9b7-740b74731d74)

**Comment by hawkeye116477** [comment]
@blocker999 A ty robiłeś tam zakupy i było wszystko ok? Bo z tego co widzę, to większość opinii jest negatywna.

**Comment by blocker999** [comment]
Nie robiłem tam zakupów tak tylko zapytałem, dobra jak coś to może być ten sklep dalej blokowany.
