### ISSUE TITLE
maendo.tv

### ISSUE THREAD

**Issue by xxcriticxx** [FiltersHeroes/KAD#37]
http://maendo.tv/LD2/index.php?title=Wspania%C5%82e%20stulecie%20/%20Muhte%C5%9Fem%20Y%C3%BCzy%C4%B1l%20-%20odc.%20220&poster=http://alltube.tv/static/normal/lopqduvah7vd.jpg#!

Zdejmij blokadę dostępu - weryfikacja tożsamości

Potwierdź dane podając numer telefonu, na który wyślemy darmowy kod dostępu.

**Comment by azet12** [comment]
już jest na liście
