### ISSUE TITLE
Błędna reguła 

### ISSUE THREAD

**Issue by MajkiIT** [FiltersHeroes/KAD#447]
@azet12 czy ta reguła jest poprawna? Na moje oko nie. 

`||alltube.tv/static/main/.gif$image`

**Comment by azet12** [comment]
Wejdź na stronę 'alltube.tv/static/main/.gif' - pojawia się fałszywy player.

**Comment by krystian3w** [comment]
Blokowane przez: https://www.alliance4creativity.com/watch-it-legally/
