### ISSUE TITLE
magiskmanager.com

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#739]
https://www.xda-developers.com/psa-magiskmanager-com-not-official-website-magisk/

**Comment by hawkeye116477** [comment]
Ale wirusów niby nie ma, przynajmniej na razie.
Podobna sprawa jest z `https://youtubevanced.com`, też nieoficjalna strona, sami hostują wszystko i sumy kontrolne plików zgadzają się z tymi z oficjalnej strony.

**Comment by xMaap** [comment]
Skoro adwcleaner.pl już jest na liście to czemu nie?

**Comment by azet12** [comment]
Nie miałbym nic przeciwko, ale dodawanie reklam do takiej "fanowskiej" strony to czyste chamstwo.

**Comment by hawkeye116477** [comment]
@azet12 W takim razie `youtubevanced.com` raczej też się kwalifikuje do dodania :smile:.
