### ISSUE TITLE
Nieprawidłowe blokowanie

### ISSUE THREAD

**Issue by xMaap** [FiltersHeroes/KAD#885]
thermomix.vorwerk.pl to żadne oszustwo

**Comment by hawkeye116477** [comment]
`https://github.com/PolishFiltersTeam/KAD/issues/784`
Czyli jak rozumiem, wcześniej się pomyliłeś. Bo też mi ta strona nie wygląda podejrzanie, oni miksery i blendery robią.

**Comment by xMaap** [comment]
@hawkeye116477 Niepamiętań wszystkiego co zgłaszam. Może i faktycznie jednak zostawić.

**Comment by krystian3w** [comment]
No to ja bym jednak zamknął, jeszcze ktoś się wpędzi w długi a tak kupi używany z olx najwyżej starszą generacje z papierowymi przepisami.

**Comment by hawkeye116477** [comment]
To na tych pokazach takie cuda pokazują, także raczej faktycznie zostawimy.
`https://www.bankier.pl/wiadomosc/Scierki-za-2000-zl-Sprzedaz-na-pokazach-ma-sie-dobrze-7218846.html`

**Comment by xMaap** [comment]
A tak w ogóle to chyba lepiej zablokować:
vorwerk.de
vorwerk.pl
Oraz
bestvac-sklep.pl

**Comment by krystian3w** [comment]
`||vorwerk.pl^
`||bestvac-sklep.pl^
`||www.hcde-sklep.com.pl^

A subdomeny to pod Kad host?
