### ISSUE TITLE
Regex pod `agency|icu|life|live|loan`

### ISSUE THREAD

**Issue by krystian3w** [FiltersHeroes/KAD#919]
```
||apps*.hooliday*.agency^
||apps*.wtflife*.life^
||app*.bigbigabum*.live^
||app*.hardmonday*.agency^
||app*.something-wrong*.agency^

||best*.whoisyourd*.agency^

||game*.sadman*.agency^
||game*.ttxssayyes*.agency^

||mobile*.funysmile*.agency^
||mobile*.harddayforal*.life^
||mobile*.trydaytoday*.live^

||play*.trydaytoday*.agency^

||prize*.greenyourday*.agency^
||prize*.ttxsr*.agency^

||reward*.harddayforal*.icu^
||reward*.linetotime*.agency^
||reward*.srli*.agency^
||reward*.trueredirect*.icu^
||reward*.whoisyourd*.icu^

||sweeps*.checkyourtime*.agency^
||sweeps*.jumpringpring*.agency^
||sweeps*.something-wrong*.agency^
||sweeps*.whoisyourd*.live^
```

to nie pasuje do schematu, więc musi zostać wildcard:

```
!||google-*.anniversarygiveawaysseries.xyz^
!||google-*.bestgadgetoffers.icu^
!||google-*.newgadgetpresents.icu^
!||google-*.smartphonesbonusoffers.icu^

**Comment by krystian3w** [comment]
```
/^https?:\/\/(app|best|mobile|prize|reward|sweeps)*\.\[a-z]{5,15}*\.(agency|icu|live)\/$document
```

ale może być błędny.

**Comment by krystian3w** [comment]
<table><tr><td></td></tr><tr><td>

```
/^https?:\/\/(.*\.|)(apps?|best|competition|game|mobile|play|prize|reward|sweeps)[0-9]{2,8}\.[a-z-]{5,22}[0-9]{1,8}\.(agency|icu|life|live)\//$~third-party,document,domain=agency|icu|life|live
```

![image](https://user-images.githubusercontent.com/35370833/61974563-1f5cea80-afe7-11e9-91a2-fb0c394140b6.png) |
--- |

</td></tr> <tr><td></td></tr> <tr><td>

```
/^https?:\/\/(.*\.)?(apps?|best|competition|game|mobile|play|prize|reward|sweeps)[0-9]{2,8}\.[a-z-]{5,22}[0-9]{1,8}\.(agency|icu|life|live)\//$~third-party,document,domain=agency|icu|life|live
```

![image(1)](https://user-images.githubusercontent.com/35370833/62032918-1d637900-b1eb-11e9-88f2-c933e463a122.png) |
--- |

</td></tr></table>



Ale  pomysł może być błędny. Regexy nie zawierają frazy `competition`.

**Comment by krystian3w** [comment]
@gwarser `domain=agency|icu|life|live|loan` jakoś daje dużo na wydajności ładowania pozostałych suffiksów internetowych?

**Comment by gwarser** [comment]
Regexa trzeba zawężać jak się tylko da, więc opcja `domain` by się przydała.

Dał byś parę sampli prawdziwych linków, to by lepiej się sprawdzało tego regexa.

>Ilustracje nie zawierają frazy `competition`.

Znaczy - poprawiłeś tekst po wygenerowaniu obrazków? Czy jakiś błąd?

Tak się zastanawiam, czy tą grupę na początku można by jakoś poprawić - `(.*\.|)`. Ja bym tu wstawił np. `\w` zamiast `.*`, żeby przypadkiem nie jadło całego URLa.

**Comment by krystian3w** [comment]
Tak po stworzeniu obrazku dopisałem "subdomenę":

`competiotionXXXX.` ("konkurs/olimpiada/wyzwanie")

---

Przykład linku, o działający raczej trudno, czasem domena pada po 1 godzinie czy do 3 dni i tylko subdomena się często powtarza.

```
http://game1130.landmolvd18.live/5628120704/?u=kvypp0n&o=cekwcnh&t=mu2-mobi.pro&f=1&fp=MRfWcAtWckSjfT3zsFxaGqxSfgAk2AT6%2BdUheLtyqX%2BAVVo94NaAxm%2F2zOJgvF7uYeR%2BStT3cVbH2VR5jzSMDvvRJBHtRLRGwWwbQccvVVRux130WgpPUO3C7ZVnyDBQZDZJ3Osk0wqJa2%2FRyzwmi5rNnr9zZH5cSnvCEfk%2FjfbuUBTWPKEyx%2FzJJL2zjc3lTdpvO9SgCAdegsyJY%2FWcUPNNU5i1A0c%2Fqzg1NSPxg0T3TeZTE%2FRIvMmbaDmiQSJb6KmkOtfTQzxjYHuZkCHFRKQPMs4GK%2FBQISvmb7i5EBPpOaJz4iSAODellsv0ex7IlNVYp7%2BMUMpbhnyPtgi2lraPILcjC%2FRrAYQcY7GlgY9b4E7alglV4cET0anmsMKPZguHiEt%2F3yNqUwO18VoXr9Mlmx8bvE9u1g5f3xCCPxsDX6IC8loNUGQd8f8MXvHyJZL4mKjwjx6cqVTWR1LgcEOBS5Ts3ajbpWihcBoEPr8YvA%2B9RslWrGlDGh7DXAVE0X0EN%2FDGL%2BvpDAyP0E7hOfA1UOKde2g5%2F7TFj4a2f3OG%2BSeyRVVkIiQTJlAIC2sTIcQwfXiBJgZEOxc3e1f%2Fi6cU%2FtQrXuHydfRv7qvWOgGHtFhJeSMmuSTkAmaiXUhqWks1pBk9dlBs0fzxCoHk%2FoUF4YQQ37n6rAJX9flGVkgQI77lsTU4Ll%2FPwSindUcOGKzWcMJOCjG7b4aTPWiIH3RkFbJ%2FPExEHbLFwv1wTYJhl29wAg0VN3PA9%2BOogwKGL59IpPMTI7L4ZjhPV95Oq6IwadeKZWFY%2BKYOJM98jnNepL4L%2FGmbY8tEPpZOYskrhvP8aClN2UbBFVZWKoNgDMsWLYvTOhwzjWeSs097bo15ny7o0dZ3Vnxul77EXe83MxuzyqEmjTijh5SZAsHrow5hJJhVc8n1BU3HIq6WCeRFU47E3gVe9yrr6ozM%2BGs1KlFbD4XMq%2FprRB%2FOIlbVYYPGvdzYWLcioIn7ZjF5AudqPT4XqK0zGOKc1rw%2B%2FruOsIfLt%2FS5aLI3bK%2B%2FBUnmZO%2BH%2FBtVCR8m7DM2ZD4yJRXiTA57P%2Bnrhcy0XSmEw28f%2Fd%2FP7ZEqQ%2Bi1sKWMY4irCA%3D%3D
```

Najbardziej zależało mi by blokowało jakby nagle przed doklejali:

`https?://www.`
`https?://www1`
`https?://www7`
`https?://wwwa`

Niby czasem też używają SSL, więc nie można założyć że to nieszyfrowany scam zawsze jest.

**Comment by gwarser** [comment]
Auć. To `\w` to też z gwiazdką i kropką. `\w` to `[A-Za-z0-9_]` ale bez `/` czy `:` to nie "wyskoczy" poza samą domenę przy porównywaniu i powinno być szybsze. `.*\.` mogło by pasować aż do rozszerzenia nazwy pliku w np. `http://domena:80/sciezka/plik.costam` i było by troszkę wolniejsze.
